### ISSUE TITLE
增加一个外呼任务，上传联系人文件后，无法初始化该任务。

### ISSUE THREAD

**Issue by wangpengli** [chatopera/cskefu#192]
# 描述

在cc界面上，增加一个外呼任务，参数随意，上传文件包含外呼电话号码。
log提示：

contact-center_1  | 2019-06-27 14:17:13.760 [CSExecutor-callout-dial-2] INFO  com.chatopera.cc.app.schedule.CallOutSheetTask - [callout sheet] start to process sheet
contact-center_1  | 2019-06-27 14:17:13.772 [CSExecutor-callout-dial-2] INFO  com.chatopera.cc.util.mobile.MobileNumberUtils - init with file [/opt/chatopera/file:/opt/chatopera/contact-center-3.9.0.war!/WEB-INF/classes!/config/mobile.data]
contact-center_1  | 2019-06-27 14:17:13.773 [CSExecutor-callout-dial-2] ERROR o.s.a.i.SimpleAsyncUncaughtExceptionHandler - Unexpected error occurred invoking async method 'public void com.chatopera.cc.app.schedule.CallOutSheetTask.run(java.lang.String,java.lang.String,java.lang.String,org.springframework.web.multipart.MultipartFile)'.
contact-center_1  | java.lang.NullPointerException: null
contact-center_1  | 	at com.chatopera.cc.app.schedule.CallOutSheetTask$SheetHandler.endElement(CallOutSheetTask.java:216)
contact-center_1  | 	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
contact-center_1  | 	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
contact-center_1  | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
contact-center_1  | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
contact-center_1  | 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
contact-center_1  | 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
contact-center_1  | 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
contact-center_1  | 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
contact-center_1  | 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
contact-center_1  | 	at com.chatopera.cc.app.schedule.CallOutSheetTask.run(CallOutSheetTask.java:93)
contact-center_1  | 	at com.chatopera.cc.app.schedule.CallOutSheetTask$$FastClassBySpringCGLIB$$28d8d7f0.invoke(<generated>)
contact-center_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
contact-center_1  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
contact-center_1  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
contact-center_1  | 	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115)
contact-center_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
contact-center_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
contact-center_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
contact-center_1  | 	at java.lang.Thread.run(Thread.java:748)

mobile.data无法找到导致，docker环境出错。
## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
这里有一个bug，有一个路径默认没有创建，第一次执行外呼任务时会创建，但是第一次外呼任务会因此失败。
然后执行第二次外呼任务，就能正常执行了。
如果还有问题，请反馈。关于呼叫中心模块，现在做的自动化还不够好，最近一个月会更新。

**Comment by wangpengli** [comment]
我这里一直创建都是失败，我同事追到了你说的bug，大概是上传联系人文件的默认路径，但似乎有的机器不行，同事反馈说是mobile.data的路径问题，但docker内war包是包含的，有点迷惑。

Samurais <notifications@github.com> 于2019年6月27日周四 下午2:31写道：

**Comment by Samurais** [comment]
上传的Excel文件格式需要按照一个格式，参考示例见附件。
[callout_chatopera_test.xlsx](https://github.com/chatopera/cosin/files/3337179/callout_chatopera_test.xlsx)

**Comment by wangpengli** [comment]
不是格式问题，是mobile.data读取路径的问题，使用resoucefile的方法，在/config/mobile.data目录找不到文件，所以导致出错。使用file绝对路径，然后将mobiledata文件放到该路径，执行是没有问题的。我在docker中新建目录，放入文件，可以执行了。没有搞明白，看似war包中也有该路径的文件。

Samurais <notifications@github.com> 于2019年6月28日周五 上午9:20写道：
