### ISSUE TITLE
使用iframe嵌套 有时候会报错 Dom未加载 js就加载了

### ISSUE THREAD

**Issue by HFLisOnceboy** [chatopera/cskefu#208]
# 描述
使用iframe嵌套 有时候会报错 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at 1wqjhy.html:10

## 现在行为
![image](https://user-images.githubusercontent.com/37856130/63633149-e95a6700-c675-11e9-9071-a2fb0657b95f.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
可以不用iframe吗？
拷贝每个网站渠道的代码，加入到你的网页中。
![image](https://user-images.githubusercontent.com/3538629/63644106-946d2e00-c713-11e9-934d-4afc5a76f4e5.png)

**Comment by HFLisOnceboy** [comment]
angular7 TS代码好像我就不知道怎么接了 ,,,

**Comment by HFLisOnceboy** [comment]
我这里用的是angular7 TypeScript 而且是在手机端  点一个按钮 然后跳到其他页面 这个聊天在其他页面出现 你给我的这个接入方式 好像只能是这个按钮 而且还是弹出框....  所以请教下这大概要怎么弄呢

**Comment by HFLisOnceboy** [comment]
我只会接入那个那个聊天窗口页面
