### ISSUE TITLE
移动客户端无法建立访客会话

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/cskefu#209]
# 描述

## 现在行为

上次发现的，部分移动设备无法打开客服系统的问题。

![image](https://user-images.githubusercontent.com/3538629/64110911-eb2ed380-cdb5-11e9-96f4-b0202fd0d0ab.png)

![image](https://user-images.githubusercontent.com/3538629/64110893-deaa7b00-cdb5-11e9-9085-59a9faf13481.png)

原因

![image](https://user-images.githubusercontent.com/3538629/64110955-0994cf00-cdb6-11e9-848d-ec96576323ed.png)

## 预期行为

# 解决方案

## 方案1

是因为在text.html 里有setTimeOut方法。
而setTimeOut方法时间参数写的1
就是1毫秒后执行这个方法。
方法里会取body元素。

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
<table border="1">
  <tr>
    <th class="tg-0lax">章</th>
    <th class="tg-0lax">节</th>
    <th class="tg-0lax">时长</th>
  </tr>
  <tr>
    <td class="tg-buh4" rowspan="3">春松客服的介绍</td>
    <td class="tg-buh4">如何使用Java开发智能客服系统</td>
    <td class="tg-buh4">1:0:0</td>
  </tr>
  <tr>
    <td class="tg-0lax">春松客服在企业的落地</td>
    <td class="tg-0lax">1:0:0</td>
  </tr>
  <tr>
    <td class="tg-buh4">春松客服的技术介绍</td>
    <td class="tg-buh4">1:0:0</td>
  </tr>
  <tr>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-buh4"></td>
    <td class="tg-buh4"></td>
    <td class="tg-buh4"></td>
  </tr>
  <tr>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
</table>

**Comment by Samurais** [comment]
<table>
  <tr>
    <th>章</th>
    <th>节</th>
    <th>时长</th>
  </tr>
  <tr>
    <td rowspan="3">春松客服的介绍</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785478331471026&type=1024&vid=5285890796113543115">如何使用Java开发智能客服系统</a></td>
    <td>1:0:0</td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785482626438322&type=1024&vid=5285890796174208504">春松客服在企业的落地</a></td>
    <td>1:0:0</td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785486921405618&type=1024&vid=5285890796206187829">春松客服的技术介绍</a></td>
    <td>1:0:0</td>
  </tr>
  <tr>
    <td rowspan="7">客服相关的基本知识</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785491216372914&type=1024&vid=5285890796236118691">客服的日常工作</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785495511340210&type=1024&vid=5285890796265703352">客服的基本知识</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785499806307506&type=1024&vid=5285890796295538521">账号体系-权限，部门和角色</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785504101274802&type=1024&vid=5285890796326774174">坐席会话的工具-拉黑，服务小结和转接</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785508396242098&type=1024&vid=5285890796387973179">即时通信及坐席自动分配</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785538461013170&type=1024&vid=5285890796727947677">企业聊天与人工质检</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785542755980466&type=1024&vid=5285890796727887112">统计报表和满意度评价</a></td>
    <td></td>
  </tr>
  <tr>
    <td>春松客服的上线及维护</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785512691209394&type=1024&vid=5285890796417069415">春松客服的编译和部署</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785516986176690&type=1024&vid=5285890796447482734">春松客服的运维管理</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785521281143986&type=1024&vid=5285890796596887008">春松客服的自动化系统测试（1）</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785534166045874&type=1024&vid=5285890796596824768">春松客服的自动化系统测试（2）</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785525576111282&type=1024&vid=5285890796625584882">春松客服的压力测试（1）</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785529871078578&type=1024&vid=5285890796625353569">春松客服的压力测试（2）</a></td>
    <td></td>
  </tr>
  <tr>
    <td>春松客服的机器人客服</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785564230816946&type=1024&vid=5285890797022829695">Chatopera云服务介绍</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785568525784242&type=1024&vid=5285890797022829724">机器人的知识库管理</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785568525784242&type=1024&vid=5285890797022829724">机器人的多轮对话及富文本消息类型</a></td>
    <td></td>
  </tr>
  <tr>
    <td rowspan="8">春松客服开发基础知识</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785547050947762&type=1024&vid=5285890796845383231">SQL快速入门</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785551345915058&type=1024&vid=5285890796845241957">春松客服数据库表及管理</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785555640882354&type=1024&vid=5285890796905914800">Java编程基础（1）</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785559935849650&type=1024&vid=5285890796905985344">Java编程基础（2）</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785585705653426&type=1024&vid=5285890796934211686">Maven项目管理</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785590000620722&type=1024&vid=5285890796934221816">搭建春松客服开发环境</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785611475457202&type=1024&vid=5285890797257385985">SpringBoot快速入门</a></td>
    <td></td>
  </tr>
  <tr>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785611475457202&type=1024&vid=5285890797257385985">项目源码讲解</a></td>
    <td></td>
  </tr>
  <tr>
    <td>春松客服的插件</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785611475457202&type=1024&vid=5285890797257385985">插件机制设计</a></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785611475457202&type=1024&vid=5285890797257385985">春松客服机器人插件解读</a></td>
    <td></td>
  </tr>
  <tr>
    <td>总结</td>
    <td><a href="https://ke.qq.com/webcourse/index.html#cid=464050&term_id=100555327&taid=4785611475457202&type=1024&vid=5285890797257385985">春松客服团队介绍及课程总结</a></td>
    <td></td>
  </tr>
</table>
