### ISSUE TITLE
[cc]点击外呼系统后的默认页面-业务概况无数据

### ISSUE THREAD

**Issue by wq11123** [chatopera/cskefu#24]
# 描述

## 现在行为

![](https://user-images.githubusercontent.com/40993206/44764231-4b76ae00-ab81-11e8-810a-fbda00841848.png)

![](https://user-images.githubusercontent.com/40993206/44764237-503b6200-ab81-11e8-8a50-53e20f8fdf4b.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
https://github.com/Samurais/chatopera.io/issues/771
