### ISSUE TITLE
后台无法得到前台聊天客户是从哪个网址进入会话的

### ISSUE THREAD

**Issue by hrh94** [chatopera/cskefu#307]
例如前台客户访问https://www.sogou.com/1.html这个页面，然后在这个页面的某处点击发起了我们系统的会话，系统后台会记录该客户是通过https://www.sogou.com/1.html这个渠道发起了会话的信息

**Comment by Samurais** [comment]
现在是通过“网站渠道”展示来访者的地址的，在来访者轨迹中，有具体的来自哪个网站的地址。
