### ISSUE TITLE
局域网内其他电脑接入网站列表可以正常发送消息，但内网穿透后 外网接入网站列表时不能发消息

### ISSUE THREAD

**Issue by maohang528** [chatopera/cskefu#310]
# 描述

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by maohang528** [comment]
外网访问客服聊天页面是能打开的 但是消息无法发送

**Comment by mukaiu** [comment]
需要开放8035和8036两个端口
