### ISSUE TITLE
集成机器人失败

### ISSUE THREAD

**Issue by xgdz** [chatopera/cskefu#316]
![}9WNCP~B_NT@@W9 %S{6G}I](https://user-images.githubusercontent.com/63387957/78975940-c5d22700-7b47-11ea-8e30-911259436755.jpg)
![QEJT3_H 0$0E90RT KNF_7G](https://user-images.githubusercontent.com/63387957/78975959-d08cbc00-7b47-11ea-932a-e0372722f0c0.jpg)
请求画红线的地址就会出现
![{6IGG KPQ(P4K$IHFJJ95}L](https://user-images.githubusercontent.com/63387957/78975998-e4d0b900-7b47-11ea-8317-d0e56a193ecb.jpg)

**Comment by kylezhang** [comment]
请再检查时间设置的问题。

**Comment by Samurais** [comment]
电脑/服务器，同步互联网NTP时间。
