### ISSUE TITLE
excel导出时报错 “文件格式和扩展名不匹配，文件可能已损坏或不安全”

### ISSUE THREAD

**Issue by zhangguanyin** [chatopera/cskefu#355]
- [
![$YJBI ~VUFLEY5ZZ6G`FY@T](https://user-images.githubusercontent.com/41132383/91928496-cfcf0f00-ed0e-11ea-9d62-6b7f375cbf59.png)

在知识库中导出数据。文件打不开，提示：excel导出时报错 “文件格式和扩展名不匹配，文件可能已损坏或不安全”

**Comment by hailiang-wang** [comment]
现在这个问题还存在吗？使用最新版本？
