### ISSUE TITLE
windows7环境下docker部署报错

### ISSUE THREAD

**Issue by hello-sly** [chatopera/cskefu#362]
# 描述
windows7环境下docker部署报错
![image](https://user-images.githubusercontent.com/65380368/94382416-30673580-016f-11eb-98e4-16d78c2422fd.png)
![image](https://user-images.githubusercontent.com/65380368/94382498-7b814880-016f-11eb-8086-d9cf241953ef.png)

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [  ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
确认 Elasticsearch 服务正常

docker-compose logs -f elasticsearch

机器硬件的配置是什么？

部署方式是按照建议的吗？
https://docs.chatopera.com/products/cskefu/deploy.html

**Comment by hailiang-wang** [comment]
该问题解决了吗？
该 Windows 操作系统及 CPU，内存，配置如何？

**Comment by hailiang-wang** [comment]
系统配置过低导致，部署需要 8GB MEM，4 Core + CPU.
