### ISSUE TITLE
会话历史中的统计功能查询不出来数据

### ISSUE THREAD

**Issue by hello-sly** [chatopera/cskefu#363]
# 描述
查询不出来东西，日志打印warn
![image](https://user-images.githubusercontent.com/65380368/94383933-ff3d3400-0173-11eb-83cc-df451cc2c139.png)

![image](https://user-images.githubusercontent.com/65380368/94383826-b08f9a00-0173-11eb-86ee-056a9d4357f3.png)

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [  ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
在演示环境 cc.chatopera.com 上有数据，需要复现。

![image](https://user-images.githubusercontent.com/3538629/94448996-26c8e680-01de-11eb-86c6-e6fe14db2368.png)
