### ISSUE TITLE
dockerfile 构建镜像异常：在安装amazon jdk corretto出现: No such file or directory

### ISSUE THREAD

**Issue by pygaaa0** [chatopera/cskefu#367]
# 描述
dockerfile安装amazon jdk corretto出现: No such file or directory
![image](https://user-images.githubusercontent.com/13269116/96071442-bce65780-0ed4-11eb-93e3-a484ed2bdf91.png)

去除RUN chmod +x /opt/install-corretto-8.sh && /opt/install-corretto-8.sh可以构建完成，但是镜像无法运行
![image](https://user-images.githubusercontent.com/13269116/96071643-24040c00-0ed5-11eb-8e6d-bc8b864ee92e.png)

环境：
![image](https://user-images.githubusercontent.com/13269116/96072270-8dd0e580-0ed6-11eb-883a-dcc17fb6f8ec.png)
C:\Users\Valiant>mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: D:\Tools\apache-maven-3.6.3\bin\..
Java version: 1.8.0_265, vendor: Amazon.com Inc., runtime: C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_265\jre
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "x86", family: "windows"

C:\Users\Valiant>java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment Corretto-8.265.01.1 (build 1.8.0_265-b01)
OpenJDK Server VM Corretto-8.265.01.1 (build 25.265-b01, mixed mode)

## 预期行为

# 解决方案

# 环境 windows

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
春松客服官方构建 docker 脚本针对 linux 环境，不支持 windows, 如果需要在 windows 上构建 docker 镜像，需要根据 脚本自动修改。

或者 使用 git bash 环境，执行脚本。因为这些脚本是在 linux bash 上测试。

**Comment by Samurais** [comment]
请了解 docker 的工作原理，构建镜像内的文件不是宿主机器内的内容，要保证在 docker 镜像内有 java 和 maven 等依赖。

**Comment by pygaaa0** [comment]
> 因为这些脚本是在 linux bash 上测试。

使用git bash  有着同样的问题，所以不知道是什么情况
![image](https://user-images.githubusercontent.com/13269116/96074408-31bc9000-0edb-11eb-9fd9-2f08bde7baba.png)

**Comment by Samurais** [comment]
那可能是一些命令， windows git bash 和 linux bash 并不一致，推荐使用 Linux 构建 docker 镜像；开发时，在 IDE 内开发 春松客服就是一个 Spring Boot 程序，是可以的。但是部署和构建镜像，强烈建议 使用 Ubuntu 16.04 或 Ubuntu 18.04, just work.

**Comment by Samurais** [comment]
使用最新代码，无法复现或已经解决。
