### ISSUE TITLE
创建 智能机器人点击`保存`出现error。

### ISSUE THREAD

**Issue by kylezhang** [chatopera/cskefu#368]
# 描述

在`https://cc.chatopera.com/`中创建 智能机器人，添加了client id与secret 之后，点击`保存`出现error。

## 现在行为
![image](https://user-images.githubusercontent.com/3679798/96358290-27e39880-1138-11eb-88be-6e9445a35ead.png)

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by xianliwang** [comment]
bot平台机器人欢迎词超过99字符，在春松客服绑定该机器人时保存报错
![image](https://user-images.githubusercontent.com/52594347/96407498-15d72800-1214-11eb-98d1-9f5b678e51a6.png)
![image](https://user-images.githubusercontent.com/52594347/96407612-5afb5a00-1214-11eb-8c0e-2a99ab374953.png)
机器人欢迎词在99字符内，在春松客服绑定该机器人时正常
![image](https://user-images.githubusercontent.com/52594347/96407710-93029d00-1214-11eb-8ccd-86dccd910d10.png)
