### ISSUE TITLE
发布春松客服 v6 版本

### ISSUE THREAD

**Issue by Samurais** [chatopera/cskefu#373]
# 描述

## 功能

* [x] 代码
* [x] docker
* [ ] 文档

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hackingchen** [comment]
能否为不同网站指定坐席？

**Comment by Samurais** [comment]
为不同网站制定坐席，在 v5 版本就通过技能组实现了。
@hackingchen

**Comment by Samurais** [comment]
新版本视频介绍:
https://chatopera.blog.csdn.net/article/details/109592612

**Comment by Samurais** [comment]
组织结构和权限文档，
https://docs.chatopera.com/products/cskefu/accounting.html
