### ISSUE TITLE
创建好多轮会话后，设计器测试正常，但是实际使用过程中丢失按钮

### ISSUE THREAD

**Issue by baoanxiaoxiong** [chatopera/cskefu#375]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/73162783/97962029-4d86c800-1def-11eb-8920-f0d39c26fd86.png">
如图所示，在设计器中，机器人回复之后，下方有注册地址链接
而实际对话窗口，则如下所示
<img width="590" alt="image" src="https://user-images.githubusercontent.com/73162783/97962137-83c44780-1def-11eb-8451-0a84f8e61f19.png">

**Comment by Samurais** [comment]
```exports.get_register```函数的返回值，params 书写错误，card是卡片信息，不是按钮。
参考：[按钮消息定义](https://docs.chatopera.com/products/chatbot-platform/conversation.html#%E6%8C%89%E9%92%AE%E6%B6%88%E6%81%AF)

**Comment by Samurais** [comment]
重新看了您的意思，是图文消息，不是按钮消息。
其中，title、thumbnail、summary和hyperlink都是必须的。

```
// 图文消息
exports.get_shangyi = async function() {
    return {
        text: "{CLEAR} 图文消息",
        params: [{
            type: 'card',
            title: "秋冬上衣优选",
            thumbnail: "https://ss0.bdstatic.com/xx.jpg",
            summary: "秋冬上衣优选秋冬上衣优选秋",
            hyperlink: "https://www.1688.com/B6AC.html"
        }]
    }
}
```
