### ISSUE TITLE
如图 一直会显示有一名客户在等待 但是只有一个手机测试 而且后台也没有任何提示

### ISSUE THREAD

**Issue by shuhaoSCode** [chatopera/cskefu#378]
# 描述

如图 一直会显示有一名客户在等待 但是只有一个手机测试 而且后台也没有任何提示
点击示忙 在切换回来 客服就能连上了

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

![截屏2020-11-07 上午10 21 05](https://user-images.githubusercontent.com/31207768/98429658-fe88ad80-20e2-11eb-8713-60f32d94247a.png)

**Comment by Samurais** [comment]
切换状态之前，客服已经掉线了，使用什么方式部署？
客服要使用 Chrome 浏览器。

**Comment by shuhaoSCode** [comment]
都是使用的chrome浏览器 使用docker部署的

**Comment by shuhaoSCode** [comment]
代码使用的osc分支 请问这个会有影响吗 还是需要使用master分支呢

**Comment by Samurais** [comment]
使用 osc 分支，master 为保留分支，不做任何用途。

**Comment by Samurais** [comment]
请帮忙补充更多信息：

1）后端服务

打印日志

```
docker-compose logs -f 
```

2) 前端

使用 chrome 浏览器，网页右键打开“检查”，查看 console log。

部署是怎么完成的，使用云主机的安全端口是否允许了 默认的 8036，8035 端口下行。

**Comment by Samurais** [comment]
3) 不适用手机

使用电脑 浏览器的情况下是否正常。

**Comment by liujianlou** [comment]
我也有同样的问题，使用docker-compose 部署

**Comment by liujianlou** [comment]
临时解决，在 agentstatus.html 中轮询模拟click点击事件
$('#agentstatus_busy').click();

**Comment by Samurais** [comment]
原因是，系统没有就绪的坐席。

搭建好系统后，需要按照以下步骤：

1) 创建组织机构
2）创建技能组
3）创建角色，并赋予坐席会话权限
4）创建账号，将账号加入技能组和角色
5）创建网站渠道，关联技能组
6）坐席账号登入，设置状态为就绪

这些在文档中有说明。

**Comment by Samurais** [comment]
增加系统初始化文档，https://docs.chatopera.com/products/cskefu/initialization.html
