### ISSUE TITLE
兜底回复是否可以和问候语一样设置

### ISSUE THREAD

**Issue by baoanxiaoxiong** [chatopera/cskefu#379]
类似__faq_hot_list

**Comment by Samurais** [comment]
登陆 https://bot.chatopera.com/dashboard

兜底回复进入机器人设置页面：

修改*兜底回复*然后保存。

![image](https://user-images.githubusercontent.com/3538629/98637745-d2c82a80-2363-11eb-94e5-c46f4417573a.png)
