### ISSUE TITLE
[cc]历史会话-等待时间过长的现象

### ISSUE THREAD

**Issue by wq11123** [chatopera/cskefu#38]
# 描述

## 现在行为
![3012796934dffc9f50175802aefb406](https://user-images.githubusercontent.com/40993206/44975196-69367f80-af94-11e8-8a56-5624b02143b3.png)
![671e6a8160f2372333f9469c08137d8](https://user-images.githubusercontent.com/40993206/44975197-6a67ac80-af94-11e8-8f2d-23a4b5a97afd.png)
![e89c5487a7c81ff88eefedb8e5b1410](https://user-images.githubusercontent.com/40993206/44975199-6b98d980-af94-11e8-999b-b9d9649edd29.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
The commit hash (`git rev-parse HEAD`)

**Comment by xianliwang** [comment]
@Samurais 企业版可以设置排队超时时间，排队超时后会有相应的提示
