### ISSUE TITLE
V6最新版创建用户没有组织机构选择

### ISSUE THREAD

**Issue by hackingchen** [chatopera/cskefu#380]
![1](https://user-images.githubusercontent.com/27922337/98932822-d18d2e00-251a-11eb-8368-4c8fcea963eb.jpg)

![2](https://user-images.githubusercontent.com/27922337/98932902-ecf83900-251a-11eb-9ede-fee48a63a63d.jpg)

**Comment by xianliwang** [comment]
演示环境是有的，您那边的截图是自己部署的地址吗？
![image](https://user-images.githubusercontent.com/52594347/103746354-f1812f80-503b-11eb-9d51-a52d0184daa1.png)
