### ISSUE TITLE
Springboot版本又回到1.5.10.RELEASE了吗

### ISSUE THREAD

**Issue by jackccjjkk** [chatopera/cskefu#381]
不是升级到springboot2了吗，最新的代码怎么使用的是1.5.10.RELEASE

**Comment by Samurais** [comment]
不升级到 spring boot 2, 原因是：1）要调整的代码太多；2）spring boot 1.x 在更新和维护，没有遇到使用问题。

**Comment by Samurais** [comment]
除非春松客服重写，否则不会考虑使用 spring boot 2, 即便是重写，也可能出现了 spring boot 3\4\5，到时候再说。
感谢关注，我们就暂时不讨论这个问题了。
