### ISSUE TITLE
本地服务网页加载特别慢是什么情况

### ISSUE THREAD

**Issue by jackccjjkk** [chatopera/cskefu#382]
本地服务网页加载特别慢是什么情况电脑配置如下
![image](https://user-images.githubusercontent.com/16814806/100619961-c890bf00-3358-11eb-89f2-3fb3bd95da2a.png)

**Comment by Samurais** [comment]
服务器是如何部署的？
服务是如何启动的？
使用 activity monitor 查看资源占用情况。

![image](https://user-images.githubusercontent.com/3538629/103898326-bbbd7300-512f-11eb-9d0e-8340f12fc1df.png)
