### ISSUE TITLE
机器人平台使用临时域名，春松客服里的配置调整

### ISSUE THREAD

**Issue by Samurais** [chatopera/cskefu#384]
# 通知

尊敬的 Chatopera 用户，您好！

应有关法律法规要求，Chatopera 在工信部的备案信息需要调整，在最终确定调整期间需要中断网络解析的情况下，我们第一时间提供了临时方案，在 chatopera.com 域名没有完成新的备案期间，请使用 cskefu.com 替换之前出现 chatopera.com 的地方。cskefu.com 的备案信息符合相关法律法规要求。

比如，文档中心 https://docs.chatopera.com 调整为 https://docs.cskefu.com。

备案时间保守估计需要三个星期，完成后我们会第一时间通知您。

此次备案后，保证 chatopera.com 可以更稳定和可靠，对因此给您带来的影响深表歉意！

# 春松客服机器人的配置调整

根据以上信息，机器人平台地址为：https://bot.cskefu.com

在春松客服里，根据部署方式不同，需要按如下调整：

## 使用官方推荐方式部署
如果您参考的如下文档部署：
https://docs.cskefu.com/products/cskefu/deploy.html

那么，只需修改 `docker-compose.yml`，增加一个环境变量，然后重启。

```
  contact-center:
    image: ${CC_IMAGE:-chatopera/contact-center:develop}
    ...
    environment:
      ...
      - BOT_PROVIDER=${BOT_PROVIDER:-https://bot.cskefu.com}
```

该环境变量就是 `BOT_PROVIDER`，如上，添加到 `contact-center` 里。

```
docker-compose up -d contact-center # 执行重启
```

## 使用自行构建的  WAR 包启动

该调整也支持环境变量 `BOT_PROVIDER`，比如 

```
export BOT_PROVIDER=https://bot.cskefu.com
java -jar contact-center.jar
```

### 创建新的机器人客服
和之前一致。

### 对于已经创建的机器人客服

对于之前已经存在的机器人，需要在重启后，先删除该机器人，然后再次绑定机器人。

**Comment by chenfantech** [comment]
安装上面的说明修改docker-compose.yml文件，重启服务后机器人平台的访问域名还是之前的。

**Comment by Samurais** [comment]
重启是使用这个命令吗？
```
docker-compose up -d contact-center
```

**Comment by Samurais** [comment]
> 安装上面的说明修改docker-compose.yml文件，重启服务后机器人平台的访问域名还是之前的。

重启是使用这个命令吗？
```
docker-compose up -d contact-center
```

**Comment by chenfantech** [comment]
是的

**Comment by luoyeqianqiu** [comment]
是的，我就是按照修改文件去改的配置文件哦

**Comment by chenfantech** [comment]
是的。



‍


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatopera/cskefu"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月10日(星期四) 下午4:23
收件人:&nbsp;"chatopera/cskefu"<cskefu@noreply.github.com&gt;;
抄送:&nbsp;"宸凡科技"<1011974692@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [chatopera/cskefu] 机器人平台使用临时域名，春松客服里的配置调整 (#384)





  
安装上面的说明修改docker-compose.yml文件，重启服务后机器人平台的访问域名还是之前的。
  
重启是使用这个命令吗？
 docker-compose up -d contact-center

**Comment by Samurais** [comment]
在机器人管理页面，打开右上角“登陆 Chatopera 云服务的 URL”是什么？进入的浏览器 URL 地址。

![image](https://user-images.githubusercontent.com/3538629/101741452-0930cb00-3b05-11eb-887c-913d20667368.png)

**Comment by luoyeqianqiu** [comment]
![image](https://user-images.githubusercontent.com/59460721/101742193-6462bd80-3b05-11eb-95f3-7443e76fbb00.png)
这个倒是对的

**Comment by chenfantech** [comment]
![image](https://user-images.githubusercontent.com/39526941/101742014-5ad95580-3b05-11eb-92d3-240a297b2c55.png)

**Comment by Samurais** [comment]
使用最新的 image 解决上述问题：

编辑 [.env](https://github.com/chatopera/cskefu/blob/osc/sample.env) 文件

保证 `CC_IMAGE` 和 `LOG_LEVEL` 的设置如下 
```
CC_IMAGE=chatopera/contact-center:develop
LOG_LEVEL=INFO
```

然后执行，

```
docker-compose pull contact-center
docker-compose up -d contact-center
```

待服务启动后，测试机器人客服。

**Comment by Samurais** [comment]
使用最新镜像，发生错误

![image](https://user-images.githubusercontent.com/3538629/101855250-1cdc4000-3b9e-11eb-8cf6-e2e930b9bda8.png)

```
cad362001b4dc555","secret":"68b45abdb98a52aadbdbbc95927e43f6","workmode":"机器人客服优先","ops":"create"} [http-nio-8035-exec-1]
contact-center_1  | 2020-12-11 10:56:41.357 INFO  c.c.c.p.c.ApiChatbotController - [create] bot with url https://bot.cskefu.com [http-nio-8035-exec-1]
contact-center_1  | 2020-12-11 10:56:41.478 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path
 [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.evictIdleConnecti
ons(JLjava/util/concurrent/TimeUnit;)Lorg/apache/http/impl/client/HttpClientBuilder;] with root cause [http-nio-8035-exec-1]
contact-center_1  | java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.evictIdleConnections(JLjava/util/concurrent/TimeUnit;)Lorg/apac
he/http/impl/client/HttpClientBuilder;
contact-center_1  |     at kong.unirest.apache.ApacheClient.<init>(ApacheClient.java:59)
contact-center_1  |     at kong.unirest.Config.buildClient(Config.java:707)
contact-center_1  |     at kong.unirest.Config.getClient(Config.java:692)
contact-center_1  |     at kong.unirest.BaseRequest.asJson(BaseRequest.java:240)
contact-center_1  |     at com.chatopera.bot.sdk.RestAPI.get(RestAPI.java:92)
contact-center_1  |     at com.chatopera.bot.sdk.Chatbot.command(Chatbot.java:184)
contact-center_1  |     at com.chatopera.bot.sdk.Chatbot.command(Chatbot.java:295)
contact-center_1  |     at com.chatopera.cc.plugins.chatbot.ApiChatbotController.create(ApiChatbotController.java:554)
contact-center_1  |     at com.chatopera.cc.plugins.chatbot.ApiChatbotController.operations(ApiChatbotController.java:111)
contact-center_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by luoyeqianqiu** [comment]
> 使用最新镜像，发生错误
> 
> ![image](https://user-images.githubusercontent.com/3538629/101855250-1cdc4000-3b9e-11eb-8cf6-e2e930b9bda8.png)
> 
> ```
> cad362001b4dc555","secret":"68b45abdb98a52aadbdbbc95927e43f6","workmode":"机器人客服优先","ops":"create"} [http-nio-8035-exec-1]
> contact-center_1  | 2020-12-11 10:56:41.357 INFO  c.c.c.p.c.ApiChatbotController - [create] bot with url https://bot.cskefu.com [http-nio-8035-exec-1]
> contact-center_1  | 2020-12-11 10:56:41.478 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path
>  [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.evictIdleConnecti
> ons(JLjava/util/concurrent/TimeUnit;)Lorg/apache/http/impl/client/HttpClientBuilder;] with root cause [http-nio-8035-exec-1]
> contact-center_1  | java.lang.NoSuchMethodError: org.apache.http.impl.client.HttpClientBuilder.evictIdleConnections(JLjava/util/concurrent/TimeUnit;)Lorg/apac
> he/http/impl/client/HttpClientBuilder;
> contact-center_1  |     at kong.unirest.apache.ApacheClient.<init>(ApacheClient.java:59)
> contact-center_1  |     at kong.unirest.Config.buildClient(Config.java:707)
> contact-center_1  |     at kong.unirest.Config.getClient(Config.java:692)
> contact-center_1  |     at kong.unirest.BaseRequest.asJson(BaseRequest.java:240)
> contact-center_1  |     at com.chatopera.bot.sdk.RestAPI.get(RestAPI.java:92)
> contact-center_1  |     at com.chatopera.bot.sdk.Chatbot.command(Chatbot.java:184)
> contact-center_1  |     at com.chatopera.bot.sdk.Chatbot.command(Chatbot.java:295)
> contact-center_1  |     at com.chatopera.cc.plugins.chatbot.ApiChatbotController.create(ApiChatbotController.java:554)
> contact-center_1  |     at com.chatopera.cc.plugins.chatbot.ApiChatbotController.operations(ApiChatbotController.java:111)
> contact-center_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

是的，最新镜像会出现这个问题，请问怎么解决呢

**Comment by Samurais** [comment]
使用最新的代码或镜像，解决了问题。

**Comment by Samurais** [comment]
现已经更新回 bot.chatopera.com
