### ISSUE TITLE
域名变更之后无法正常创建机器人

### ISSUE THREAD

**Issue by luoyeqianqiu** [chatopera/cskefu#385]
## 来自

- 公司：
- 产品：

# 描述

## 现在行为
域名更改后按照教程修改了环境变量，然后无法正常创建机器人
![image](https://user-images.githubusercontent.com/59460721/101737627-1b5c3a80-3b00-11eb-8860-b833e7af4cd9.png)
![image](https://user-images.githubusercontent.com/59460721/101737747-421a7100-3b00-11eb-9cc9-fc891c9fb44a.png)
![image](https://user-images.githubusercontent.com/59460721/101740476-d63a0780-3b03-11eb-887f-7b53b85a1839.png)

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
Duplicated with https://github.com/chatopera/cskefu/issues/384
