### ISSUE TITLE
平台的测试对话不支持空间显示

### ISSUE THREAD

**Issue by luoyeqianqiu** [chatopera/cskefu#387]
## 来自

- 公司：
- 产品：

# 描述

## 现在行为
![image](https://user-images.githubusercontent.com/59460721/101881737-cee03000-3bcf-11eb-87a8-98e234136f57.png)
![image](https://user-images.githubusercontent.com/59460721/101881754-d30c4d80-3bcf-11eb-8b9f-767530d928c3.png)
测试器上的对话能正常显示控件，但平台上的多轮对话无法正常显示控件
## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
机器人平台的测试对话功能和多轮对话设计器是同一个接口，只是展示兼容性不同，需要统一为多轮对话设计器。但是这两个从 API 返回数据是一样的。见多轮对话设计器和机器人平台的测试对话的 API 返回 JSON。
