### ISSUE TITLE
ResponseBody 返回xml而非json，改json有其他副作用吗？

### ISSUE THREAD

**Issue by fastuser999** [chatopera/cskefu#390]
## 来自

- 公司：
- 产品：

# 描述
系统里面@ResponseBody返回的是xml不是json,我修改了pom去掉了
<dependency>
-            <groupId>com.fasterxml.jackson.dataformat</groupId>
-            <artifactId>jackson-dataformat-xml</artifactId>
-        </dependency>
请问会有什么副作用吗？

## 预期行为

# 解决方案

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
具体接口具体分析，建议用 json 时，复制原来的接口，重新创建新的接口，不要调整旧的接口。
