### ISSUE TITLE
初始化数据库失败.

### ISSUE THREAD

**Issue by lichen-y** [chatopera/cskefu#392]
## 来自

- 公司：
- 产品：

# 描述
![image](https://user-images.githubusercontent.com/45346369/103646105-0e622800-4f94-11eb-8d17-582ed4d4b8a3.png)
![image](https://user-images.githubusercontent.com/45346369/103646111-11f5af00-4f94-11eb-903b-37271f07f672.png)
初始化数据库的时候这里ip获取的是mysql 初始化失败.

## 功能

# 环境

## 操作系统

- [ √] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
请描述部署方法。建议按照文档进行部署：https://docs.chatopera.com/products/cskefu/deploy.html

**Comment by Samurais** [comment]
自定义数据请修改环境变量
https://github.com/chatopera/cskefu/blob/b49184c33d0860a4daa130397b4068423edd1a71/docker-compose.yml#L38
