### ISSUE TITLE
希望支持多商户嵌入

### ISSUE THREAD

**Issue by yonghao9531** [chatopera/cskefu#394]
## 来自

- 公司：
- 产品：

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
具体是怎么样的操作？要怎么样潜入多商户？
现在在春松客服内，创建组织机构，每个组织机构创建技能组，一个组织机构就可以映射为一个商户。
然后创建坐席，绑定到商户的技能组。

再在组织机构内创建管理员；管理员和超级管理员创建渠道，绑定到商户技能组。

这样用，不是也能支持多商户吗？了解春松客服组织机构权限和角色：https://docs.chatopera.com/products/cskefu/accounting.html

请具体描述需求。

**Comment by yonghao9531** [comment]
我目前采用得是这种方式，我的想法是界面贴近im，不止有访客，还有用户得概念，能显示昵称，头像等

**Comment by yonghao9531** [comment]
客服不在线，留言得方式，之后也没法回复了

**Comment by Samurais** [comment]
“用户的概念”，这里用户是什么。在春松客服里，我们主要用：访客、坐席、管理员、高级客服、客户主管和超级管理员几个更清楚的表述方式。

**Comment by Samurais** [comment]
> 客服不在线，留言得方式，之后也没法回复了

这个问题可以新建立 Issue 解决，每个 Issue 我们只关注一个讨论。感谢！

**Comment by yonghao9531** [comment]
用户的概念 ，就是同一用户登录，只会有一个会话，并支持离线消息

**Comment by Samurais** [comment]
请使用访客或坐席来表述。
