### ISSUE TITLE
历史会话不显示数据。

### ISSUE THREAD

**Issue by feiniao2020** [chatopera/cskefu#395]
会话信息》历史会话、当前会话、排队队列、访客留言，经过测试不显示数据。

后台：http://106.53.130.148:8035/login.html   账号：admin  密码：admin1234

测试网站》http://b001.yun.9sem.cn/

**Comment by Samurais** [comment]
请说明部署的过程，部署的方式是根据我们提供的文档操作的吗？
https://docs.chatopera.com/products/cskefu/deploy.html

**Comment by feiniao2020** [comment]
后台不知道谁操作了，现在创建用户不了、创建部门不了、网站渠道点击报错》Whitelabel Error Page，This application has no explicit mapping for /error, so you are seeing this as a fallback.
![QQ截图20210107000655](https://user-images.githubusercontent.com/71068505/103790531-4b094e80-507c-11eb-96f2-1f6472cd62c8.jpg)
![QQ截图20210107000628](https://user-images.githubusercontent.com/71068505/103790535-4c3a7b80-507c-11eb-8ef3-94c98878989a.jpg)
![QQ截图20210107000552](https://user-images.githubusercontent.com/71068505/103790537-4cd31200-507c-11eb-9cd5-61688b8f5e13.jpg)

**Comment by pengwei1986** [comment]
@xianliwang 在哪里添加技能组？

**Comment by hailiang-wang** [comment]
系统 -> 组织机构 -> 创建部门。

![image](https://user-images.githubusercontent.com/3538629/127107540-ad80056c-646b-4640-b48a-1e44c80c16c1.png)

开启【启用技能组】。
![image](https://user-images.githubusercontent.com/3538629/127107612-99467423-ec98-4e32-a743-71b3ac9c5bf6.png)
