### ISSUE TITLE
启动contact-center 服务报错

### ISSUE THREAD

**Issue by shengdiandian** [chatopera/cskefu#396]
## 来自

- 公司：
- 产品：春松客服3.0版本

# 描述

根据部署文档 docker-compose up -d contact-center后 mysql服务起不来   服务日志报错
contact-center_1  | [run]  ./001.alter_uk_consult_invite.sql  ...
contact-center_1  | 2021-01-07 11:08:33 [upgrade] run MySQL DB upgrade script ./001.alter_uk_consult_invite.sql ...
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | ERROR 1049 (42000) at line 1: Unknown database 'cosinee'
contact-center_1  | Fail to resolve mysql database instance.

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ x] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本
3.0版本

**Comment by Samurais** [comment]
春松客服 3.0 版本已经不维护。请使用最新的版本。

**Comment by shengdiandian** [comment]
> 春松客服 3.0 版本已经不维护。请使用最新的版本。

想测试使用呼叫中心模块，新版本如何试用呢

**Comment by Samurais** [comment]
新版本呼叫中心不开源，参考 https://docs.chatopera.com/products/cskefu/callcenter.html

联系商务洽谈。
