### ISSUE TITLE
用户不能创建、部门不能创建、网站渠道页面报错问题。

### ISSUE THREAD

**Issue by feiniao2020** [chatopera/cskefu#397]
后台：http://106.53.130.148:8035/login.html 账号：admin 密码：admin1234

2021-12-28 安装最新版春松客服，后把账号密码发布到GitHub请教问题之后，昨日下午在登录后发现系统被人操作了导致如下问题。
1、 用户不能创建
2、 部门不能创建
3、 网站渠道页面报错。
![QQ截图20210107000655](https://user-images.githubusercontent.com/71068505/103892457-9710cd80-5126-11eb-83ac-8696973d6c80.jpg)
![QQ截图20210107000628](https://user-images.githubusercontent.com/71068505/103892466-99732780-5126-11eb-89f1-01dbc43e4e37.jpg)
![QQ截图20210107000552](https://user-images.githubusercontent.com/71068505/103892469-9a0bbe00-5126-11eb-81b4-5394a60a9b71.jpg)

**Comment by Samurais** [comment]
在服务器上执行，```docker-compose logs -f ``` 查看错误日志。
不要上传敏感信息。

**Comment by Samurais** [comment]
通过文档熟悉常见操作，https://docs.chatopera.com/products/cskefu/deploy.html

通过购买春松客服大讲堂熟悉运维和定制化开发，https://docs.chatopera.com/products/cskefu/training.html

**Comment by Samurais** [comment]
使用脚本 [scripts/flush.sh](https://github.com/chatopera/cskefu/blob/osc/scripts/flush.sh) 重置数据库。相当于刷新本地安装环境，数据全部清除。
同时这个脚本也会在清除数据后，重启服务，初始化数据库。
在使用前，请了解这个脚本的影响：数据清除，不可恢复。如在生产环境，请将 cskefu 文件夹整体备份。
