### ISSUE TITLE
vue使用"@chatopera/sdk": "^2.5.5"出现跨域问题

### ISSUE THREAD

**Issue by chanpanzzn** [chatopera/cskefu#400]
## 来自

- 公司：苏州黑莓信息
- 产品：智能问答

# 描述

Access to XMLHttpRequest at "https:/bot.chatopera.con api/vl/chatbot/5ffbf2.../faq/query' fron onigin 'http/Localhost:8080' has been blocked by cros plicy Respnse to preflight request doesn't pass access control check: No 'Access Control-Allow-Origin' header is present on the requested resource.

# 环境

## 操作系统

-  Windows

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
“https:/bot.chatopera.con” ？ 不应该是 https:/bot.chatopera.com 吗？
这个问题和春松客服的关系是什么？

**Comment by Samurais** [comment]
@chatopera/sdk 是在后端使用 Node.js 运行环境的，不是在前端使用的。
