### ISSUE TITLE
聊天信息  multiMediaDialogWin 一直获取不到

### ISSUE THREAD

**Issue by lichen-y** [chatopera/cskefu#401]
## 来自

- 公司：
- 产品：

# 描述
![image](https://user-images.githubusercontent.com/45346369/104427357-19354200-55be-11eb-998c-d77ae75f94d0.png)

这里一直获取不到 一直在来电弹屏.

## 功能

# 环境

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

Git commit hash (`git rev-parse HEAD`)

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by Samurais** [comment]
部署的操作系统，春松客服版本，浏览器的console.log 有无报错。
这些信息请提供一下！

**Comment by Samurais** [comment]
请提供一下解决方案，或者关闭原因。
感谢！
