### ISSUE TITLE
客户离线后，客服能留言

### ISSUE THREAD

**Issue by helxm** [chatopera/cskefu#403]

**Comment by hailiang-wang** [comment]
请提供合理的需求描述，比如访客登录时提供邮箱，客服留言发送到邮箱。
因为访客对话窗口默认没有登录功能，不能用浏览器做为唯一的设备认证。

**Comment by hailiang-wang** [comment]
提出问题，并给出你理想的、有建设性的、可行的解决方案。

**Comment by helxm** [comment]
用途场景：小程序的H5页面（其他场景也是可行的）
访客识别：小程序在跳转客服链接增加参数（手机号、用户名），手机号唯一识别，若有带有手机号参数，春松系统自动创建联系人，并在接下来的会话中关联此联系人
客服留言： 在能识别客户后，客服可以给此客户发留言
客户查看留言： 客户再次通过客服链接来到系统，可以查看留言

安全性问题： 加入oauth2.0授权接口

**Comment by hailiang-wang** [comment]
该过程比较繁琐，企业搭建春松客服要上线小程序。

在访客打开聊天控件，可以要求填写 email。客服回复留言直接发送邮件，这个方案不能接受吗？
