### ISSUE TITLE
[cc] cc.chatopera.com创建呼叫计划初始化没有成功

### ISSUE THREAD

**Issue by wq11123** [chatopera/cskefu#41]
# 描述
cc.chatopera.com创建呼叫计划初始化没有成功
![](https://user-images.githubusercontent.com/3679798/44944568-e4b8f500-ae0b-11e8-8699-5dd14f435862.png)

## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by Samurais** [comment]
这个问题是已知问题，在服务初次启动后会遇到。
可以再创建一次解决。
