### ISSUE TITLE
运行时，各种包找不到

### ISSUE THREAD

**Issue by reynold-Yang** [chatopera/cskefu#410]
java: package org.junit does not exist
java: package mondrian.mdx does not exist
java: cannot find symbol
  symbol:   class Resolver
  location: package mondrian.olap.fun
java: package mondrian.olap.type does not exist

有很多，不知道时哪里出了问题，求帮助

**Comment by hailiang-wang** [comment]
参考开发环境搭建
https://docs.chatopera.com/products/cskefu/osc/engineering.html

基础知识不足，购买《春松客服大讲堂》


https://ke.qq.com/course/464050

**Comment by reynold-Yang** [comment]
感谢 现在是新的报错  错误: 找不到或无法加载主类 com.chatopera.cc.app.Application  求帮助
