### ISSUE TITLE
开启Nginx 配置https时报443端口冲突的问题

### ISSUE THREAD

**Issue by etaqi** [chatopera/cskefu#413]
配置文件    nginx/conf.d/default.conf

server {
	listen 443 ssl;
	server_name xxxxxx.com;

    root /usr/share/nginx/html;
    client_max_body_size 100M;
	
	ssl_certificate /certs/server.pem;
	ssl_certificate_key /certs/server.key;

    
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://contact-center:8035; 
    }

    location /socket.io { proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://contact-center:8036; 
    }
}
按照配置文档修改 .env 设置 CC_SOCKET_PORT=443
然后 docker-compose restart  发现443端口是启用了，但是nginx并没有启用。
查看了下docker-compose.xml 配置文件发现应该直接调用  
docker-compose up -d nginx 。
我们先关闭所有的容器 docker-compose down 
但是，此时启动nginx发现会报端口冲突.
最后的解决方案是。保持 .env中的CC_SOCKET_PORT 不变。
直接调用docker-compose up -d nginx  启动整个项目。
但是项目里面蹦出来了其他的问题，比如无法聊天，
暂时不知道什么原因

**Comment by hailiang-wang** [comment]
先理解原理：

nginx 443 反向代理 contact-center 

```
/ --> contact center 容器:8035 
/socket.io --> contact center 容器:8036
```
CC_SOCKET_PORT  是 contact-center 在网页链接 socketio 使用的，故需要指向 服务器 nginx 443 端口，而不是 contact center 容器8036。

关于冲突，docker-compose down 后，使用 docker network 命令查看相关的 network 也被删除了，否则手动执行删除。

**Comment by hailiang-wang** [comment]
解决方案参考：
https://github.com/chatopera/cskefu/issues/414

**Comment by baihuajituan** [comment]
CC_SOCKET_PORT对应的端口  如果要修改成 443  在 application.properties 里面是修改 uk.im.server.port 吗？
