### ISSUE TITLE
配置网站渠道后报错

### ISSUE THREAD

**Issue by SkorpiosL** [chatopera/cskefu#415]
## 来自

- 公司：
- 产品：

# 描述
将客服系统docker方式部署到linux环境下 配置完网站渠道后报错
![image](https://user-images.githubusercontent.com/32902343/110308006-8a332c00-803a-11eb-8d1a-20e1d8a54e77.png)

## 功能

# 环境

## 操作系统

- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

osc

## OpenSource by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
@mukaiu 现在 testclient 的接入还是以前的方式：

https://github.com/chatopera/cskefu/blob/fe4ddd24053a8c35cd95ee7135fd213f5eef2433/contact-center/app/src/main/resources/static/testclient.html#L12

在渠道的控制台也是

![image](https://user-images.githubusercontent.com/3538629/110308538-37a63f80-803b-11eb-865e-c1229ff436df.png)

**Comment by hailiang-wang** [comment]
在演示环境 cc.chatopera.com 没问题

![image](https://user-images.githubusercontent.com/3538629/110308680-62909380-803b-11eb-8db6-a1073b236ece.png)


@SkorpiosL 请详细介绍配置过程，敏感信息请打码。

**Comment by SkorpiosL** [comment]
您那边的测试环境我测试过 没有问题可以正常打开
这是我这边出现问题的后台日志
![image](https://user-images.githubusercontent.com/32902343/110309065-da5ebe00-803b-11eb-8719-9414d1c8c6c6.png)

**Comment by hailiang-wang** [comment]
MySQL 数据库容器日志有报错吗？
`docker-compose logs -f mysql`

确定数据库已经使用 https://github.com/chatopera/cskefu/blob/osc/contact-center/config/sql/cosinee-MySQL-slim.sql 初始化，当第一次启动时，也会默认执行初始化。

建议使用工具，如 MYSQL Workbench 连接 MySQL 检查数据库 `cosinee` 及表存在。

**Comment by hailiang-wang** [comment]
连接数据库：
https://docs.chatopera.com/products/cskefu/osc/engineering.html#mysql

系统初始化：
https://docs.chatopera.com/products/cskefu/initialization.html

**Comment by hailiang-wang** [comment]
春松客服 Testclient 的配置：
名称和网站地址的值都必须是 `localhost`，你的配置是什么？

**Comment by SkorpiosL** [comment]
数据库我这边检查没有问题

网站配置也是localhost

**Comment by hailiang-wang** [comment]
使用春松客服最新版已经解决
