### ISSUE TITLE
ubuntu20.04 启动报错

### ISSUE THREAD

**Issue by xihongjian** [chatopera/cskefu#418]
# 描述

## 现在行为
 ERROR o.s.boot.context.embedded.tomcat.TomcatStarter - Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'webMetricsFilter' defined in class path resource [io/micrometer/spring/autoconfigure/web/servlet/WebMvcMetricsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.micrometer.spring.web.servlet.WebMvcMetricsFilter]: Factory method 'webMetricsFilter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]: Factory method 'requestMappingHandlerMapping' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mvcConversionService' defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.format.support.FormattingConversionService]: Factory method 'mvcConversionService' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chatMessageEsRepository': Cannot resolve reference to bean 'elasticsearchTemplate' while setting bean property 'elasticsearchOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchDataAutoConfiguration.class]: Unsatisfied dependency expressed through method 'elasticsearchTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticsearchClient' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'elasticsearchClient' threw exception; nested exception is java.lang.IllegalStateException: java.net.UnknownHostException: elasticsearch: Temporary failure in name resolution
## 预期行为

# 解决方案

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by hailiang-wang** [comment]
请描述部署方式，过程

**Comment by xihongjian** [comment]
问题已经解决是因为在虚拟机上启动elasticsearch docker有问题。解决办法是直接运行elasticsearch保证服务启动就OK了。

**Comment by hailiang-wang** [comment]
很有可能是内容或 CPU 的资源不足导致，可以更新一个环境，启动 elasticsearch docker。
资源占用参考：
https://docs.chatopera.com/products/cskefu/deploy.html

**Comment by xihongjian** [comment]
1.安装ubuntu20.04作为宿主机器。
2.启动镜像
docker-compose up -d mysql
docker-compose up -d elasticsearch
docker-compose up -d redis
docker-compose up -d activemq
问题：1. elasticsearch文件夹权限问题。解决后容器启动正常。
2.反馈的问题。telnet 9300  9200 均失败。  但elasticsearch不报错。
解决办法：直接下载elasticsearch包在宿主机上运行。然后就正常了。

**Comment by hailiang-wang** [comment]
使用容器 ES，在宿主机器上，连接 ES 端口不是默认的，参考

https://github.com/chatopera/cskefu/blob/fe4ddd24053a8c35cd95ee7135fd213f5eef2433/docker-compose.yml#L101
