### ISSUE TITLE
网站渠道 机器人+人工客服模式下 弹窗不能使用

### ISSUE THREAD

**Issue by limmishere** [chatopera/cskefu#421]
## 描述

docker部署春松客服
设置网站渠道和智能机器人
网站渠道主要就是设置了技能组，智能机器人进行了绑定，如图：
![image](https://user-images.githubusercontent.com/48585743/111272760-fd0d5a00-866d-11eb-87b8-99e0d5a5de6a.png)

使用文字链代码进行测试，智能机器人和人工客服都可以正常使用，如图
![image](https://user-images.githubusercontent.com/48585743/111271040-9edf7780-866b-11eb-898c-f2658563a5b1.png)

嵌入网站中，弹窗使用，智能机器人和人工客服都不可使用
智能客服：
![image](https://user-images.githubusercontent.com/48585743/111272760-fd0d5a00-866d-11eb-87b8-99e0d5a5de6a.png)

切换到人工坐席：
![image](https://user-images.githubusercontent.com/48585743/111271686-802db080-866c-11eb-829a-53d28b68b3b2.png)

使用docker logs 查看，报错如下：
![image](https://user-images.githubusercontent.com/48585743/111271687-802db080-866c-11eb-852e-fb8e5a816150.png)

而如果不绑定智能机器人，那么弹窗功能和文字链代码表现的是一样的，都是可以正常的和人工客服进行交流。

我使用青松客服提供的演示环境：https://cc.chatopera.com/ 进行复现，发现是可以复现的，也就是说演示环境如果开了人工+机器人，嵌到网页的弹窗在我这边测试来看，都是要报错的，且表面上报的错误是一样的，后台就不清楚了。

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by limmishere** [comment]
机器人的设置传错图了
![Uploading image.png…]()

**Comment by hailiang-wang** [comment]
请重新上传一下，这个图片

![image](https://user-images.githubusercontent.com/3538629/111286053-bd9a3a00-867c-11eb-9e09-78a6b82cf447.png)

**Comment by mukaiu** [comment]
![image](https://user-images.githubusercontent.com/7746790/111411355-5f6d6580-8715-11eb-9c64-b551988d8f03.png)

嵌入页面url包含 `#` 导致 socket 参数丢失

**Comment by mukaiu** [comment]
@limmishere 已修复此问题

**Comment by hailiang-wang** [comment]
# 升级办法

## Docker-compose 中 contact-center image
`https://github.com/chatopera/cskefu/blob/osc/docker-compose.yml`

 Docker-compose 中 contact-center image 默认就是使用 
```chatopera/contact-center:develop```

假设您没有做修改

## 停止服务

```docker-compose down ```

## 拉群新镜像

```
docker-compose pull

```

## 重启服务

```
docker-compose up -d

```

**Comment by hailiang-wang** [comment]
# 升级后检查版本
登录，右上角点击“关于产品”
![image](https://user-images.githubusercontent.com/3538629/111462718-b8f78380-8759-11eb-832c-685fb9357e80.png)

查看版本信息

![image](https://user-images.githubusercontent.com/3538629/111462775-cad92680-8759-11eb-8f75-8c9bb48c3caf.png)

BUILD 里的 commid ID 和 Github 春松客服代码 commit ID 一致

![image](https://user-images.githubusercontent.com/3538629/111462852-ddebf680-8759-11eb-8fb5-0471a3d53f7d.png)
