### ISSUE TITLE
cs_stream_file性能问题

### ISSUE THREAD

**Issue by neversuspend** [chatopera/cskefu#423]
现在图片文件是不是都存到cs_stream_file这张表里面了，里面有个mediumblob类型字段，表越来越大，感觉会影响性能哈

有没有什么优化手段，是不是可以不存mediumblob

**Comment by hailiang-wang** [comment]
这个我们比较清楚，性能在 MySQL 层面需要使用读写分离，集群等形式。
数据库可能成为瓶颈，在我们目前客户的使用上，暂时没有因 BLOB 问题产生。
