### ISSUE TITLE
自定义打包 WAR 部署后，后台启动为报错，登录页面打不开

### ISSUE THREAD

**Issue by SeventeenOld** [chatopera/cskefu#424]
后台启动为报错，登录页面打不开，全是空白，f12竟然全是200

**Comment by hailiang-wang** [comment]
部署方式请说明，使用哪个文档完成的部署。
操作系统等信息。

**Comment by hailiang-wang** [comment]
请优化 Issue 标题内容。

**Comment by SeventeenOld** [comment]
使用这个文档部署的,部署在云服务器上了,项目启动没有任何报错





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
部署方式请说明，使用哪个文档完成的部署。
 操作系统等信息。

**Comment by SeventeenOld** [comment]
正常启动,但是访问页面的时候,页面加载不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
部署方式请说明，使用哪个文档完成的部署。
 操作系统等信息。

**Comment by SeventeenOld** [comment]
登陆页面打开是这个样子的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
部署方式请说明，使用哪个文档完成的部署。
 操作系统等信息。

**Comment by hailiang-wang** [comment]
请粘贴部署文档的链接，运行后的贴图。
后台日志的详情。

如果缺少基础技能，包括 docker 的使用，java的基础，请报名课程。

https://ke.qq.com/course/464050?tuin=6780672d

**Comment by SeventeenOld** [comment]
附件为我们的配置文件,截图1为项目结构.截图2位打包后的结构.目前用shell脚本启动,没问题,访问页面不报错,但是空白页.













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatopera/cskefu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet 'dispatcherServlet' [http-nio-8035-exec-1]  (#424)





 
请粘贴部署文档的链接，运行后的贴图。
 后台日志的详情。
 
如果缺少基础技能，包括 docker 的使用，java的基础，请报名课程。
 
https://ke.qq.com/course/464050?tuin=6780672d

**Comment by hailiang-wang** [comment]
Sorry, nothing is attached in this GitHub Issue. Please view it in a browser from desktop.

**Comment by SeventeenOld** [comment]
链接：http://note.youdao.com/noteshare?id=903a23d1a17a0a68ffb4b1135f4df764




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月25日(星期四) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
Sorry, nothing is attached in this GitHub Issue. Please view it in a browser from desktop.

**Comment by hailiang-wang** [comment]
该机器的防火墙或安全规则，开启对 8035，8036 端口的下行访问权限

**Comment by SeventeenOld** [comment]
已经开启访问权限




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
该机器的防火墙或安全规则，开启对 8035，8036 端口的下行访问权限

**Comment by hailiang-wang** [comment]
部署环境参考：
https://docs.chatopera.com/products/cskefu/deploy.html

你搭建的不是开发环境吧？

**Comment by hailiang-wang** [comment]
看到了，你是自定义的 jar 包。
应用启动较慢，大约 2 分钟。

```
INFO  c.c.socketio.SocketIOServer - SocketIO server started at port: 8036 [nioEventLoopGroup-2-1]
INFO  com.chatopera.cc.Application - Started Application in 35.319 seconds (JVM running for 42.876) [main]
```

待日志有如下信息后访问登录页面。

**Comment by SeventeenOld** [comment]
https://docs.chatopera.com/products/cskefu/osc/engineering.html


是按照这个开发环境搭建的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
部署环境参考：
 https://docs.chatopera.com/products/cskefu/deploy.html
 
你搭建的不是开发环境吧？

**Comment by hailiang-wang** [comment]
在 IDEA 中可以正常启动吗？

**Comment by SeventeenOld** [comment]
有哪个信息,你看我给你发的链接服务器后台日志信息,倒数第二行就是,最后一行是我访问8035的时候弹出来的信息




另外如果我用win7本地运行的话,会有一个报错,https://github.com/chatopera/cskefu/issues/408




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hai Liang ***@***.***&gt;; 
发送时间: 2021年3月26日(星期五) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO  o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1]  (#424)





 
在 IDEA 中可以正常启动吗？

**Comment by hailiang-wang** [comment]
先在这台机器上，用 部署文档部署一套默认的春松客服实例，
https://docs.chatopera.com/products/cskefu/deploy.html

确定春松客服可以正常使用。
如果不能正常使用，则代表该机器网络存在问题。

如果可以正常使用，则代表打包有问题。

**Comment by hailiang-wang** [comment]
> 链接：http://note.youdao.com/noteshare?id=903a23d1a17a0a68ffb4b1135f4df764
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Hai Liang ***@***.***&gt;; 发送时间: 2021年3月25日(星期四) 下午4:05 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [chatopera/cskefu] 2021-03-25 11:19:18.709 INFO o.a.c.c.C.[.[localhost].[/] - Initializing Spring FrameworkServlet &#39;dispatcherServlet&#39; [http-nio-8035-exec-1] (#424) Sorry, nothing is attached in this GitHub Issue. Please view it in a browser from desktop. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请将 Issue 描述信息尽可能的放在 GitHub Issue 内，对于社区而言，我们愿意支持是因为信息可以沉淀，要知道免费的使用开源软件需要你也可以做贡献，那么发现 BUG，报告问题，也就是一种有价值的贡献。
