### ISSUE TITLE
客户坐席无法自动接入

### ISSUE THREAD

**Issue by q312700254** [chatopera/cskefu#432]
## 描述

1、按教程本地搭建项目
2、新建账号，勾选多媒体坐席，分配坐席权限
3、新建渠道，并打开渠道网页链接，输入文字内容，debuger控制台上有显示消息。
问题：
      网页发送文字消息,后台坐席显示空，无法坐席聊天，需要手动关闭就绪，再打开，才能自动接入，当用户离开之后，下一位用户又无法自动接入，需要再次操作关闭就绪再打开，才能接入。。。
![image](https://user-images.githubusercontent.com/12796130/112644810-c9f27400-8e80-11eb-8cc0-5626bb0b770f.png)
<img width="810" alt="image" src="https://user-images.githubusercontent.com/12796130/112644888-dd054400-8e80-11eb-97df-d873a9983808.png">

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
duplicated with https://github.com/chatopera/cskefu/issues/425

**Comment by mukaiu** [comment]
@q312700254 渠道和客服的技能组设置分别是什么样？

**Comment by hailiang-wang** [comment]
@q312700254 请提供原因，该问题是否解决，如何解决的呢？

**Comment by hailiang-wang** [comment]
经验证，为初始化的原因，没有加技能组。建立技能组，绑定技能组并加入坐席后，该服务正常。
部署后需要认证使用初始化文档。
https://docs.chatopera.com/products/cskefu/initialization.html
