### ISSUE TITLE
坐席就绪状态无法接入访客

### ISSUE THREAD

**Issue by shenxinquan2016** [chatopera/cskefu#434]
## 现在行为
1、坐席就绪且示闲状态，访客无法接入，提示“正在排队，请稍候,在您之前，还有 1 位等待用户。”，如图：
[![cCDpXn.png](https://z3.ax1x.com/2021/03/29/cCDpXn.png)](https://imgtu.com/i/cCDpXn)

2、需要坐席切换状态为非就绪再切回来，或者示忙再切回来，访客才可以接入

不管是我自己部署，还是 github 演示都存在此问题

## 预期行为
坐席就绪且状态示闲，有游客就可以直接介入

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
完成系统初始化，认真阅读文档 https://docs.chatopera.com/products/cskefu/initialization.html

**Comment by hailiang-wang** [comment]
duplicated with https://github.com/chatopera/cskefu/issues/432
