### ISSUE TITLE
漏洞：任意文件读取？

### ISSUE THREAD

**Issue by johnseed** [chatopera/cskefu#435]
## 现在行为
访问URL　http://127.0.0.1/res/voice.html?id=/../../../etc/resolv.conf  返回指定文件内容  
![image](https://user-images.githubusercontent.com/48501700/113109506-a476b900-9238-11eb-9158-e78436a2e8dc.png)

## 预期行为
不返回无关文件内容
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ √] Linux(Debian, CentOS, Ubuntu, etc.)

## 解决方案
检查参数中的路径  
https://github.com/chatopera/cskefu/blob/62d06de6c3ef4b1bc66877a69a8a1bd680041752/contact-center/app/src/main/java/com/chatopera/cc/controller/resource/MediaController.java#L105
## 代码版本

44a20cd6b03a5a4f2085f7d1536fb3068869cc17
## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
@mukaiu Pls take a look.

**Comment by hailiang-wang** [comment]
问题在 demo 实例复现

[https://cc.chatopera.com/res/voice.html?id=/../../../etc/resolv.conf](https://cc.chatopera.com/res/voice.html?id=/../../../etc/resolv.conf)

![image](https://user-images.githubusercontent.com/3538629/113110245-70e85e80-9239-11eb-9e39-15be1b38c4ef.png)

**Comment by hailiang-wang** [comment]
解决方案：因为该 API 没有被使用，删除该 API。
遍历其他 API 后，不存在该问题。
