### ISSUE TITLE
系统管理员登录后，系统里没有智能机器人功能菜单

### ISSUE THREAD

**Issue by zhmh2020** [chatopera/cskefu#436]
菜单如下图：

<img width="287" alt="WX20210407-194715@2x" src="https://user-images.githubusercontent.com/8707429/113862043-80881a00-97da-11eb-9a03-bda8d66508af.png">

**Comment by hailiang-wang** [comment]
请说明代码版本，源码打包方式，运行方式。

**Comment by hailiang-wang** [comment]
演示环境：
![image](https://user-images.githubusercontent.com/3538629/113862667-4a976580-97db-11eb-8a9c-e6e0bf55891e.png)


自行打包过程中，按照文档安装插件。

https://github.com/chatopera/cskefu/tree/osc/public/plugins

**Comment by zhmh2020** [comment]
源码版本7.0.1，使用idea软件本地运行

**Comment by hailiang-wang** [comment]
> 演示环境：
> ![image](https://user-images.githubusercontent.com/3538629/113862667-4a976580-97db-11eb-8a9c-e6e0bf55891e.png)
> 
> 自行打包过程中，按照文档安装插件。
> 
> https://github.com/chatopera/cskefu/tree/osc/public/plugins

参考上述链接安装插件。
