### ISSUE TITLE
客服登录默认状态问题

### ISSUE THREAD

**Issue by ArioWei** [chatopera/cskefu#440]
1.客服登录后默认状态是在线，实际未在线。
2.访客那边总是提示有人排队。
3.消息不能自动指定到客服。

2和3可能是由1问题导致。

**Comment by hailiang-wang** [comment]
参考初始化，https://docs.chatopera.com/products/cskefu/initialization.html

尤其注意，测试时，不要用 admin 作为客服。

另外，需要使用截图等做详细的描述。

**Comment by sdwflmw** [comment]
同遇到此问题。
2.访客那边总是提示有人排队。
3.消息不能自动指定到客服。
Docker 部署的，自建账号，客服状态正常，但是不能自动接待访客，切换状态再切回来才能接待

**Comment by hailiang-wang** [comment]
> 同遇到此问题。
> 2.访客那边总是提示有人排队。
> 3.消息不能自动指定到客服。
> Docker 部署的，自建账号，客服状态正常，但是不能自动接待访客，切换状态再切回来才能接待

1）应用部署完成后，进行初始化
https://docs.chatopera.com/products/cskefu/initialization.html

2）使用最新的版本，参考升级
https://docs.chatopera.com/products/cskefu/osc/maintainence.html

**Comment by sdwflmw** [comment]
问题已解决，
注意几点。1 部门必须创建，需要创建技能组
2. 坐席放部门底下
3. 添加渠道网站时需要指定技能组到创建的部门

**Comment by hailiang-wang** [comment]
上周末更新了组织机构，角色和账号信息显示。
建议更新到最新版本。
