### ISSUE TITLE
春松客服，机器人进行多轮对话，点击产品列表无法发送text文本

### ISSUE THREAD

**Issue by zjfzwx** [chatopera/cskefu#441]
//脚本文件:
+ 产品列表
_ ^getProducts()
//函数:
exports.getProducts = async function() {
return {
text: "我们有以下产品",
params: [{
label: "1.苹果",
type: "qlist",
text: "苹果的种类"
},
{
label: "2.猕猴桃",
type: "qlist",
text: "猕猴桃的种类"
}
]
}
}
在春松客服，用户聊天界面无法发送用户点击的产品列表信息

**Comment by mukaiu** [comment]
最新代码已修复 @zjfzwx

**Comment by zjfzwx** [comment]
> 最新代码已修复 @zjfzwx

可以了，非常感谢
