### ISSUE TITLE
坐席空闲，但是用户请求会话一直在排队中，没办法分配到空闲的坐席

### ISSUE THREAD

**Issue by ataojohn** [chatopera/cskefu#442]
## 描述
刚通过docker安装好的系统，一切都很顺利，创建了坐席，登陆后用户请求会话坐席是空闲的但是用户端仍然提示排队中，只有把坐席的状态重置一下才能接入坐席

## 操作系统
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by ataojohn** [comment]
通过日志分析，结合最新的代码发现分配坐席时目前只支持指定坐席，或者指定技能组，对于不指定技能组的分配策略那段代码注释掉了，因此设置插件的时候指定技能组就能正常分配了

**Comment by mukaiu** [comment]
@ataojohn 使用最新版本测试下

**Comment by ataojohn** [comment]
好的 非常感谢
















在 2021-05-30 22:19:16，"Mukaiu" ***@***.***> 写道：

@ataojohn 使用最新版本测试下
