### ISSUE TITLE
删除创建非合规用户，因只有一个组织存在，而不能删除该用户

### ISSUE THREAD

**Issue by ArioWei** [chatopera/cskefu#444]
![image](https://user-images.githubusercontent.com/41034256/119337617-a2255e00-bcc1-11eb-85ba-c99d7782add4.png)

**Comment by hailiang-wang** [comment]
在创建表单中，检查用户不为空。
该空用户为网络延迟时，系统用户在前端连续点击提交并创建下一个导致。
在后端 API 以及前端界面操作时考虑到检查状态

**Comment by mukaiu** [comment]
截图中界面是组织管理，删除用户在用户管理进行。
