### ISSUE TITLE
新建智能机器人时出错

### ISSUE THREAD

**Issue by Hanfan-hub** [chatopera/cskefu#445]
新建智能机器人时会出现这个错误
![image](https://user-images.githubusercontent.com/72958782/119450651-cedf8100-bd66-11eb-96b8-f80f947daa1d.png)
，但我的服务器和春松客服的时间是正确的，服务器处于联网状态，该聊天机器人已经创建，clientId和Secret也是正确的。
求回复！！！

**Comment by hailiang-wang** [comment]
SDK 常见错误，https://docs.chatopera.com/products/chatbot-platform/integration/faq.html
在后台使用 docker-compose 打印日志：

```
docker-compose logs -f
```

**Comment by hailiang-wang** [comment]
这个问题后来解决了吗？
@Hanfan-hub

**Comment by Hanfan-hub** [comment]
解决了，你也遇到了？加我微信帮你看看什么原因，以后互帮互助！&nbsp; 微信号：hanfan84




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatopera/cskefu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月7日(星期一) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatopera/cskefu] 新建智能机器人时出错 (#445)





 
这个问题后来解决了吗？
 @Hanfan-hub

**Comment by hailiang-wang** [comment]
我是春松客服团队的开发者，解决了就好。
方案您可以添加到评论，感谢！
