### ISSUE TITLE
系统管理下，修改管理员的密码，再次登录后，系统管理下：用户和组 及渠道管理等菜单出不来

### ISSUE THREAD

**Issue by jandy0414** [chatopera/cskefu#448]
![error1](https://user-images.githubusercontent.com/35617197/122343947-d6b2cf80-cf78-11eb-9306-92407d07222b.png)

**Comment by jandy0414** [comment]
https://cc.chatopera.com/  
线上版本，我试了一下，也一样出不来了。（把密码在改回去，也一样出不来了）

**Comment by mukaiu** [comment]
超级管理员信息需进入 个人信息里修改
