### ISSUE TITLE
阿里云 Tengine 方向代理导致网页客服客户端，经常不出现

### ISSUE THREAD

**Issue by yangmqit** [chatopera/cskefu#453]
## 概述

挂载网页的客服客户端，经常不出现
![image](https://user-images.githubusercontent.com/26617650/126586600-41d9b509-35c6-4526-b7fe-b2cd6a232f22.png)

报错如下
![image](https://user-images.githubusercontent.com/26617650/126586614-5c044419-255a-4cd7-aec7-6d7ff72a86eb.png)
![image](https://user-images.githubusercontent.com/26617650/126586619-af0b1280-5f32-4cf1-9152-30a63239e0a4.png)

## 操作系统

- [ ] macOS or Mac OSX
- [] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

CC_IMAGE=chatopera/contact-center:ae4f9ab

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
从客户端浏览器上看，又如下问题：
```
index.html:30 GET https://xxxxx.com/im/1tzbe9.html net::ERR_ABORTED 502 (Bad Gateway)
```

使用浏览器 Chrome

需要进步一提供春松客服后台日志，在刷新页面时，当不出现智能客服控件，有没有错误？
```
cd 春松客服
docker-compose logs -f contact-center
```

@yangmqit

**Comment by hailiang-wang** [comment]
经排查，该原因系阿里云 AFW 设置了安全策略导致，Tengine 方向代理服务屏蔽了部分客服聊天控件的加载请求，原因是该页面被频繁访问，防火墙认为发生了攻击，该事件随机。需要和阿里云开工单详细询问。
