### ISSUE TITLE
机器人回答客户问题不允许点击需要客户输入完整信息

### ISSUE THREAD

**Issue by kirahw** [chatopera/cskefu#461]
您好!
       部属完成机器人后,向机器人提问问题,机器人也根据题库检索相关问题反馈给客户,但是客户却不能点击,需要客户自己再手动根据机器人反馈打全问题

![image](https://user-images.githubusercontent.com/72481352/130378152-079fa3a1-572a-4db6-bcc1-2fa16c10d2e9.png)

**Comment by hailiang-wang** [comment]
该问题是曾经的 BUG，已经在 2 个月前解决了。
请保证用了最新的春松客服版本，升级参考：
https://docs.chatopera.com/products/cskefu/osc/maintainence.html

**Comment by hailiang-wang** [comment]
该问题在 5 月 12 日就解决了。现在您用的部署方式是什么？用的代码版本是什么？

FIX 代码参考
https://github.com/chatopera/cskefu/commit/7991317457dde6df105ea3be37529d4ceb9766c7

**Comment by kirahw** [comment]
用的是docker容器部属的,已经更新了最新版本还是这样

![image](https://user-images.githubusercontent.com/72481352/130379804-1de391b5-e5cb-4050-a1f9-1e15f8786676.png)
![image](https://user-images.githubusercontent.com/72481352/130379848-82353872-5b93-41e6-b749-c5274bc8ecab.png)
![image](https://user-images.githubusercontent.com/72481352/130379934-8ce77cd8-95f5-4528-804c-abd4a1443f36.png)
![image](https://user-images.githubusercontent.com/72481352/130379943-af80ea75-3afd-4e51-9e9a-662b1e49744a.png)

**Comment by hailiang-wang** [comment]
您用的，是这个版本 eb644a022c42e72b44068344e77b595427833116

![image](https://user-images.githubusercontent.com/3538629/130380279-98b5ceb5-1912-40b4-8653-f2dd6f3806f9.png)


这个是 4 月份的，确保使用最新的版本。请认真阅读 https://docs.chatopera.com/products/cskefu/osc/maintainence.html

当前最新的版本是：
![image](https://user-images.githubusercontent.com/3538629/130380377-adc3e348-bf43-44e1-984d-f83b6b5e78ca.png)

**Comment by kirahw** [comment]
好的，谢谢！升级的确解决了之前问题
