### ISSUE TITLE
点击页面响应很慢 CPU经常100%很卡

### ISSUE THREAD

**Issue by elicscc** [chatopera/cskefu#462]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
请提供部署方式和运行机器配置。

**Comment by hailiang-wang** [comment]
最低配置见 https://docs.chatopera.com/products/cskefu/deploy.html

**Comment by elicscc** [comment]
使用你们文档中的 docker-compose up -d contact-center  进行的部署启动

**Comment by elicscc** [comment]
配置如下 8核 8G 50G  centos 7.5

**Comment by hailiang-wang** [comment]
几乎是最低配置，内存低了一些。
建议升到 16GB
