### ISSUE TITLE
客户端点开客服每次都进入的排队   ，发现只有刷新后台的页面才会正常接入客服

### ISSUE THREAD

**Issue by elicscc** [chatopera/cskefu#463]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
安装成功后，系统初始化
https://docs.chatopera.com/products/cskefu/initialization.html

设置有接待访客能力的坐席，就绪状态才会自动分配。

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130419874-544f9f73-6735-4972-ac95-62ec36e271b3.png)
![image](https://user-images.githubusercontent.com/59130064/130419910-fa3137b3-f9db-4cdc-8922-baa3c4a2cbae.png)
我已经配置过了 还是不行 当前排队人数也不对 应该是1   
在我刷新浏览器后才出现了对话列表 不清楚是不是bug

**Comment by hailiang-wang** [comment]
如果配置都对，证明 socketio 没有连接上。

1）打开访客端对话浏览器的 web console，查看 console log。
2）打开坐席端对话浏览器的 web console，查看 console log。

检查二者日志有有无 error 信息。

socketio用来推送消息，从服务端向浏览器。

**Comment by hailiang-wang** [comment]
如果使用了 HTTPS，参考

https://chatopera.blog.csdn.net/article/details/105820829

https://github.com/chatopera/cskefu/issues/414

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130421110-894f2d75-5d7a-40d6-9134-b25b7d002c32.png)
我看了控制台都没有 error 信息。

**Comment by hailiang-wang** [comment]
使用超级管理员，设置这个网页绑定到一个技能组。
这个技能组有“坐席工作台”权限的坐席人员，在线就绪。

**Comment by hailiang-wang** [comment]
系统设置，网页渠道，接入，客服信息，绑定单一技能组。

![image](https://user-images.githubusercontent.com/3538629/130427520-b102afc9-ca0d-4161-bf79-b0add6c6964a.png)
