### ISSUE TITLE
请问使用了证书  nginx怎么转发到春松客服

### ISSUE THREAD

**Issue by elicscc** [chatopera/cskefu#464]
## 描述

这个是我的nginx配置  我试了打开客户端窗口没有反应
nginx在另一台机器上 
       location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://172.16.227.97:8035;
    }

    location /socket.io {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_pass http://172.16.227.97:8036;
    }
   

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130432300-02ae710c-926e-4128-9816-ca30e7da39fe.png)
配置后还是没反应

**Comment by hailiang-wang** [comment]
访客端使用 HTTPS 协议，可以收到和发送消息？

坐席端使用 HTTPS 协议，收不到？也发不出去？

**Comment by elicscc** [comment]
使用了https 都不能发送和接收

**Comment by hailiang-wang** [comment]
参考一下：
https://github.com/chatopera/cskefu/issues/414

理解端口转发的规则，尤其是：
春松客服 CC_SOCKET_PORT 的设置。

**Comment by hailiang-wang** [comment]
页面可以加载打开，只是收发消息不行？

**Comment by mukaiu** [comment]
客户端使用 dev tool 看下 ws 连接端口是否为 443 @elicscc

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130537563-42d3db53-984e-407d-b72f-b9c7392c3936.png)
您看看对不对

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130537825-6f8f9d4d-9da1-4523-b0d7-01a3a34e133c.png)

**Comment by mukaiu** [comment]
是使用 docker 部署吗？调整 .env 中 CC_SOCKET_PORT=443

**Comment by elicscc** [comment]
请问修改sample.env 后使用命令docker-compose restart 就可以了吗

**Comment by mukaiu** [comment]
是 .env 文件，docker-compose up -d 就行

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130542492-5193dcf6-af3b-4528-8556-017973cef641.png)
![image](https://user-images.githubusercontent.com/59130064/130542617-9329d32c-93d3-4ee8-bdb1-450b765cc8a8.png)

如图端口修改成443了  但是发请求的时候还是会在域名后加8036 不清楚什么问题

**Comment by mukaiu** [comment]
先 down 再 up 试试，另外确认 .env 文件名

**Comment by elicscc** [comment]
按照你说的方法试了  还是不行 域名后还是会拼接上8036

**Comment by mukaiu** [comment]
docker-compose ps 内容贴出来看看

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130545236-ac139fb0-7c6a-4e53-8615-a761574efa93.png)

**Comment by mukaiu** [comment]
看情况是 .env 文件未生效

**Comment by elicscc** [comment]
我改的是这个文件： sample.env  请问对吗

**Comment by elicscc** [comment]
![image](https://user-images.githubusercontent.com/59130064/130551049-c7e09f9e-59c3-4fb6-9e32-74805d19b6d2.png)
使用ip是正常的

**Comment by mukaiu** [comment]
需要修改的文件是 .env ，如不存在需把 sample.env 复制一份为 .env ，参考部署文档

**Comment by hailiang-wang** [comment]
@elicscc 可以了吗？

**Comment by dynn123456** [comment]
不行

**Comment by hailiang-wang** [comment]
> 不行

如遇到相似问题，请创建新的 Issue 进行描述。
