### ISSUE TITLE
我修改的java项目的代码 重启后没生效 请问应该怎么更新到docker

### ISSUE THREAD

**Issue by elicscc** [chatopera/cskefu#467]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com
我通过替换目录文件发现没有效果
请问修改的代码应该怎么更新到docker
以下是我启动的命令
docker-compose up -d contact-center

**Comment by hailiang-wang** [comment]
更改代码，更新到 docker，需要生成新的 contact-center docker 镜像。
参考脚本：
https://github.com/chatopera/cskefu/blob/osc/contact-center/admin/build.sh

**Comment by elicscc** [comment]
有没有本地文件部署的？

**Comment by hailiang-wang** [comment]
你是指用 WAR 包启动？
java -jar server.war 是可以的，参考
https://github.com/chatopera/cskefu/blob/osc/contact-center/Dockerfile

建议使用 docker，同时如果你的代码是对春松客服的通用的修改，建议提交 PR 到 https://github.com/chatopera/cskefu

这样，会得到持续的更新和 fix。
