### ISSUE TITLE
在idea中添加 server.context-path=/****,或者是打包后部署到web容器带项目名称访问，页面和相关样式404

### ISSUE THREAD

**Issue by baihuajituan** [chatopera/cskefu#470]
如果不添加项目名称的话，比如 127.0.0.1:8035 ,正常访问，而添加了项目名称后，比如：kefu，访问： 127.0.0.1:8035/kefu   登录后的页面和样式就404了。

前台页面 的路径使用的都是绝对路径，能否改成自定义路径？

**Comment by hailiang-wang** [comment]
目前，我们没有这个改变 context-path 的指南。
但是我知道有的春松客服用户是更改成功了，但是花了多少精力我就不知道了。

从技术上，还可以从反向代理角度考虑。

另外，这个需求并不多见，有多大意义呢？
因为容器服务的流行，大部分的应用越小越稳定，容易维护，不建议将多个应用放在一个 WAR 内。
