### ISSUE TITLE
机器人客服自动回复图片无法显示

### ISSUE THREAD

**Issue by benben17** [chatopera/cskefu#471]
## 现在行为
机器人客服回复图片无法显示，通过观察发现，返回的图片地址为相对地址无域名

**Comment by hailiang-wang** [comment]
请回答一下：

机器人客服是集成 Chatopera 云服务吗？

该回复是来自于问答对吗？

在问答对中，有几个答案？这个图片的答案是图文消息类型的答案吗？

如果是图文消息，这个是第几个答案？

目前，春松客服正准备支持知识库的多答案，多类型。您的回答，会帮助我们尽快梳理出，支持的程度和速度。

**Comment by benben17** [comment]
> 请回答一下：
> 
> 机器人客服是集成 Chatopera 云服务吗？
>  是的 
> 该回复是来自于问答对吗？
> 是的
> 在问答对中，有几个答案？这个图片的答案是图文消息类型的答案吗？
>  只有一个答案多个答案回复为空，图片的答案是图文消息
> 如果是图文消息，这个是第几个答案？
>  只有一个答案
> 目前，春松客服正准备支持知识库的多答案，多类型。您的回答，会帮助我们尽快梳理出，支持的程度和速度。

**Comment by hailiang-wang** [comment]
# related with #468

**Comment by hailiang-wang** [comment]
该问题已经解决，请使用春松客服最新版本。

升级参考[文档](https://docs.chatopera.com/products/cskefu/osc/maintainence.html#%E7%B3%BB%E7%BB%9F%E5%8D%87%E7%BA%A7)。


最新的 版本 

```
CC_IMAGE=chatopera/contact-center:f8059ae
```
