### ISSUE TITLE
首页客服的坐席状态，刷新后丢失。

### ISSUE THREAD

**Issue by baihuajituan** [chatopera/cskefu#472]
一个就绪的客服，按流程来说不主动取消 就绪状态，应该是一直就绪的。现在本地的情况是刷新页面后就绪状态就成非就绪了！

**Comment by baihuajituan** [comment]
刷新完成，到websocket重连不到1秒钟。

**Comment by baihuajituan** [comment]
但是我看官网部署的就没有这个问题，怎么刷新 就绪还是就绪

**Comment by baihuajituan** [comment]
目前是怀疑github与gitte的逻辑不一样，gitte的代码是有这个问题，

**Comment by hailiang-wang** [comment]
不建议频繁刷新，如果10秒内连续刷新，会认为客服没有就绪。
