### ISSUE TITLE
 后台支持wss 链接吗？

### ISSUE THREAD

**Issue by baihuajituan** [chatopera/cskefu#473]
服务器开启https后，socket以wss://   链接报错

**Comment by hailiang-wang** [comment]
所谓的服务器开启 https，是什么意思？

支持！和 HTTP 协议配置类似。


如果使用 nginx 做反向代理，需要配置 `    location /socket.io { proxy_set_header Upgrade $http_upgrade; ...`

参考 https://github.com/chatopera/cskefu/blob/osc/nginx/conf.d/default.conf

**Comment by baihuajituan** [comment]
现在，服务器使用了https 证书，页面正常访问但是 socket 都报链接
错

**Comment by hailiang-wang** [comment]
可能是调整 .env 文件，

.env 中 CC_SOCKET_PORT=443

可以解决。


参考：

https://github.com/chatopera/cskefu/issues/414

https://github.com/chatopera/cskefu/issues/464

**Comment by hailiang-wang** [comment]
配置后，使用 docker-compose up -d 重启服务。

**Comment by hailiang-wang** [comment]
现在解决了吗？

**Comment by baihuajituan** [comment]
这是配置ssl之后的socket报错
![lALPDiCpwK23OZvNARTNBVY_1366_276](https://user-images.githubusercontent.com/46338363/133017145-bfeba878-01e7-46ba-aee6-cd4500aa50a2.png)    
nginx配置是参考的这个，但是server的监听不改成8036吗》我看链接直接是8036，还有 proxy_pass 必须公网ip吗？
server {
    listen 443 ssl;
    server_name cc.chatopera.com;
    root /usr/share/nginx/html;
    client_max_body_size 100M;

    ssl_certificate /certs/cc.chatopera.com.cer;
    ssl_certificate_key /certs/cc.chatopera.com.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://contact-center:8035; 
    }

    location /actuator {
  return 403 "403: Target API is blocked.";

    }

    location /socket.io { 
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $host;
  proxy_http_version 1.1;
  proxy_pass http://contact-center:8036; 
    }
}

**Comment by hailiang-wang** [comment]
> 可能是调整 .env 文件，
> 
> .env 中 CC_SOCKET_PORT=443
> 
> 可以解决。
> 
> 参考：
> 
> #414
> 
> #464

参考这个修改 .env 中 CC_SOCKET_PORT，然后重启服务。

**Comment by baihuajituan** [comment]
这边事windows服务器安装docker有点麻烦。所以直接用nginx做的代理   wss://域名+8036/socket.io/       这是wss访问，但是nginx配置监听443只是对网页来说的吧， 不需要在监听公网域名的8036吗？

**Comment by baihuajituan** [comment]
CC_SOCKET_PORT对应的端口 如果要修改成 443 在 application.properties 里面是修改 uk.im.server.port 吗？

**Comment by hailiang-wang** [comment]
PLEASE READ THIS.
https://github.com/chatopera/cskefu/issues/464

.env FILE [配置文件 .env](https://docs.chatopera.com/products/cskefu/deploy.html#%E5%85%8B%E9%9A%86%E4%BB%A3%E7%A0%81)

**Comment by hailiang-wang** [comment]
这些回答是基于部署方式是按照文档解答的：
https://docs.chatopera.com/products/cskefu/deploy.html

建议使用 docker 部署，如果你修改了源码，重新构建 docker，参考：
https://github.com/chatopera/cskefu/blob/osc/contact-center/admin/build.sh

**Comment by hailiang-wang** [comment]
该问题解决了吗？如果解决请关闭 Issue。感谢！

**Comment by baihuajituan** [comment]
wss的问题参考链接解决了，但是现在 网站渠道的生成地址 不是https的链接，而是原来的http链接！！！

**Comment by hailiang-wang** [comment]
得到网站渠道的 URL 后，你手动改一下：
http-&gt;https




——————
https://bot.chatopera.com
企业聊天机器人平台


------------------ Original ------------------
From: 落故衣 ***@***.***&gt;
Date: Tue, Sep 14, 2021 9:35 AM
To: chatopera/cskefu ***@***.***&gt;
Cc: Hai Liang Wang ***@***.***&gt;, Assign ***@***.***&gt;
Subject: Re: [chatopera/cskefu]  后台支持wss 链接吗？ (#473)






wss的问题参考链接解决了，但是现在 网站渠道的生成地址 不是https的链接，而是原来的http链接！！！

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by baihuajituan** [comment]
手动改之后，的挂载页面是报错的， 渠道页面生成的地址是 http://域名:80/im/****.html         应该生成  https://域名:443/im/****.html

**Comment by baihuajituan** [comment]
ImController  的loader 里面判断  request.getServerPort() == 80    这个判断没进， 获取到的是80端口但是没改成443......导致之后倒是按80传的数据

**Comment by hailiang-wang** [comment]
> ImController 的loader 里面判断 request.getServerPort() == 80 这个判断没进， 获取到的是80端口但是没改成443......导致之后倒是按80传的数据

使用 docker 没有这个问题，docker 中有一个网络端口映射。里面看是 8035，外面随便配置，即便里面看 URL 是 80，从方向代理中依然可以使用 443，因为 SSL 是在反向代理中实现，不是在 contact-center 容器上。
