### ISSUE TITLE
pug 默认访问页面怎么配置？

### ISSUE THREAD

**Issue by baihuajituan** [chatopera/cskefu#474]
目前项目的默认访问是 /login  ，如何配置pug模板的默认访问页面呢？

**Comment by hailiang-wang** [comment]
基础开发技能，请购买春松客服大讲堂

https://github.com/chatopera/cskefu#%E5%9C%A8%E7%BA%BF%E5%9F%B9%E8%AE%AD%E8%A7%86%E9%A2%91

Pugjs 相关的请查看 Pugjs 社区文档, https://www.pugjs.cn/api/getting-started.html

欢迎提交使用 Bug 或通用的需求，不同类型的 Issue 参考：

https://github.com/chatopera/cskefu/issues/new/choose
