### ISSUE TITLE
jpa 每一个sql第一次调用 需要4~5s,看是否可以通过修改配置解决这个问题，运行环境腾讯云linux服务器

### ISSUE THREAD

**Issue by MSU-666** [chatopera/cskefu#476]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [x] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
服务是使用春松客服发布的 Docker 运行的吗？

**Comment by hailiang-wang** [comment]
@MSU-666 请问现在是什么状态，问题解决了吗？
