### ISSUE TITLE
春松客服工具可以插入下图右侧这些入口和文档吗

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#481]
Labels: 帮助， 创建者: 王海良@Chatopera
# 描述

来自 Chatopera智能客服-客户群02 （微信群或私聊）对话记录

`王海良@Chatopera`: 以上创建工单  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-09 14:35:51)*
`王海良@Chatopera`: 我想咨询一下，春松客服工具可以插入下图右侧这些入口和文档吗？ 哪里可以查询到操作教程？  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-09 14:36:21)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

**Comment by hailiang-wang** [comment]
示例参考：https://oh-my.cskefu.com/im/text/0nhckh.html

和 HUAWEI 的不太一样，如果要一样，需要改源码。
