### ISSUE TITLE
请问contact-center使用脚本打包后跑不起来,日志一直提示No such file or directory

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#485]
在windows上,运行在docker里.

![ce9f471a7caa90ff0844c3013ce04b7](https://user-images.githubusercontent.com/3538629/137423387-89cbca8b-4d5b-4040-b34f-6d7d9c9e9456.png)

**Comment by houlr** [comment]
我是使用contact-center/admin/build.sh脚本打包出一个镜像:dockerhub.qingcloud.com/chatopera/contact-center:develop,然后改了docker-compose.yml

**Comment by hailiang-wang** [comment]
拉取春松客服最新的代码，然后使用 ` contact-center/admin/build.sh` 进行构建。
这次更新了 contact-center/Dockerfile，参考 9b09839

@houlr

**Comment by houlr** [comment]
> 这个问题解决了吗？现在服务可以启动了？ @houlr

您好,我拉取了最新的代码,修改 .env 文件并创建了docker-compose.custom.yml.重新build之后还是提示: No such file or directory.
![微信图片_20211018152600](https://user-images.githubusercontent.com/43536079/137686761-ecdd6898-4bc6-41a6-9323-c0d27b207ab6.png)
![微信图片_20211018152814](https://user-images.githubusercontent.com/43536079/137686915-0a8e827e-12fe-4ab8-8818-1825930f73a9.png)
