### ISSUE TITLE
渠道绑定单一技能组 请问这个在哪里

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#487]
Labels: 帮助， 创建者: 王海良
# 描述

来自 Chatopera智能客服-客户群02 （微信群或私聊）对话记录

`王海良`: 初始化了吗？坐席人员的角色，需要有【坐席工作台】的权限。另外，渠道绑定单一技能组。技能组包括客服人员。  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-20 16:02:55)*
`东东东`: 这个已经创建了  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-20 16:02:56)*
`东东东`: 渠道绑定单一技能组 请问这个在哪里？  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-20 16:03:50)*
`王海良`: 超级管理员，创建网页渠道时，先进入【客服部】，从右上角切换组织机构到客服部。  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-20 16:04:31)*
`王海良`: 绑定技能组  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-20 16:07:31)*
`东东东`: 我先试试，谢谢您这边的耐心解答  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-20 16:07:34)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

## 上海星韵信息科技有限公司

https://www.shxingyun.com/

![image](https://user-images.githubusercontent.com/3538629/138053779-64befdcd-dea2-4bcf-bf58-a5300a1739e8.png)

![image](https://user-images.githubusercontent.com/3538629/138053799-987331dd-a45d-4f85-a208-9221e4ba14f3.png)

![image](https://user-images.githubusercontent.com/3538629/138053823-188f8af1-ee9a-4e8a-904f-d386778cea09.png)

**Comment by hailiang-wang** [comment]
经过查看，该春松客服实例初始化配置有问题，后续优化 -
1） 在启动后，加入示例数据；
2）在文档中，详细描述配置角色的过程；
3）录制视频介绍初始化过程。

# 角色配置

* 新建角色
* 添加用户到角色

![image](https://user-images.githubusercontent.com/3538629/138195101-05a3cc7f-e326-4e69-b82b-cabe7e5d508a.png)

* 为角色赋予权限
![image](https://user-images.githubusercontent.com/3538629/138195190-565761c9-280a-419b-ade2-437df24b37cf.png)

**被添加的账号需要重新登录，这个账号才能看到新赋予的资源。**

* 网页渠道绑定到单一技能组
![企业微信截图_16347226819777](https://user-images.githubusercontent.com/3538629/138195232-f8858103-9605-417b-861b-d9c849c7c1f6.png)

* 测试
登录客服和访客，客服是否分配成功，是否弹屏。

![image](https://user-images.githubusercontent.com/3538629/138195386-81007b34-0c66-4ad7-9612-36e52a831dd3.png)
