### ISSUE TITLE
在系统管理中系统角色里新增角色后点击左侧角色权限设置权限，但是权限并没有真实设置到该角色上

### ISSUE THREAD

**Issue by zhangpf41** [chatopera/cskefu#488]
在设置权限过程中，一开始登录admin账户默认是我的企业，在系统管理中系统角色里新增角色后点击左侧角色权限设置权限，但是权限并没有真实设置到该角色上，除服通过切换从我的企业切换到新的组织架构才能设置该角色在改组织架构上的权限。

![1634723942(1)](https://user-images.githubusercontent.com/10841391/138072442-479c97b1-5920-4e7d-bc11-f51c87f4d08a.png)
一般大家这样添加的权限

**Comment by zhangpf41** [comment]
![1634723994(1)](https://user-images.githubusercontent.com/10841391/138072569-baf6cd97-18d4-4de7-a0df-1d9fa5f0c2d4.png)
zh这里有一个工单模块，但是当我切换用户组工单部分就不见了还需要重新设置权限，导致用户提问无法正常弹出
![1634724044(1)](https://user-images.githubusercontent.com/10841391/138072801-0666429c-6cc0-4a5d-90cb-49a237ca884e.png)

**Comment by hailiang-wang** [comment]
related with https://github.com/chatopera/cskefu/issues/487
