### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by zidingz** [chatopera/cskefu#489]
Hey there!

I belong to an open source security research community, and a member (@noobpk) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by hailiang-wang** [comment]
@zidingz 
Just add it. Thanks for your advice and look forward to the report .

(cc @huntr-helper)

**Comment by noobpk** [comment]
@hailiang-wang Can you validate the report on huntr?

**Comment by hailiang-wang** [comment]
What is huntr, would you append the report link here. Thanks

**Comment by noobpk** [comment]
Maybe the information is missing somewhere.
You can access the report here: https://huntr.dev/bounties/3874c055-f348-4b57-bcb2-7135b2ac568b/

**Comment by noobpk** [comment]
> Maybe the information is missing somewhere.
> You can access the report here: https://huntr.dev/bounties/3874c055-f348-4b57-bcb2-7135b2ac568b/

@hailiang-wang pls tell me if you cannot access the report. Thanks
