### ISSUE TITLE
怎么解决 部署后502

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#490]
Labels: 帮助， 创建者: 王海良
# 描述

来自 Chatopera智能客服-客户群02 （微信群或私聊）对话记录

`华`: 部署后502  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:01:11)*
`华`: 怎么解决  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:01:14)*
`华`: 高手们  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:01:19)*
`颜涛/Colour`: nginx配置问题  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:04:25)*
`华`: 怎么解决  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:04:43)*
`华`: 有东西，登录后台等不进去  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:06:02)*
`华`: 打开也是没有  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-22 17:06:21)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

**Comment by hailiang-wang** [comment]
这个问题解决了吗？请更新一下状态，感谢！
