### ISSUE TITLE
Title: 用一句话陈述事情，保证言简意赅，比如问题简述及 root cause 日志语句，更容易获得帮助

### ISSUE THREAD

**Issue by sumool** [chatopera/cskefu#496]
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
请更新一下 issue 内容和标题，感谢！
