### ISSUE TITLE
mysql是什么版本的

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#502]
Labels: 帮助， 创建者: 王海良
# 描述

来自 Chatopera智能客服-客户群02 （微信群或私聊）对话记录

`王海良`: 以上 1 条创建任务  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-11-16 11:36:09)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

**Comment by hailiang-wang** [comment]
中间件版本，参考：
https://github.com/chatopera/cskefu/blob/osc/docker-compose.yml

但是，强烈建议使用春松客服发布的 docker image 搭建服务。Just work。学习容器知识，省去一些麻烦。
