### ISSUE TITLE
docker-compost启动服务uuid相关报错

### ISSUE THREAD

**Issue by leszz9527** [chatopera/cskefu#504]
contact-center_1  | ----------------------------------------------------------------
contact-center_1  | 2021-10-31 00:38:07.049 WARN  o.h.id.UUIDHexGenerator - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead [localhost-startStop-1]

**Comment by leszz9527** [comment]
centos 7环境

**Comment by leszz9527** [comment]
contact-center_1  | 00:37:34.265 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a Integer[]
contact-center_1  | 00:37:34.265 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.lang.Long;@3d494fbf
contact-center_1  | 00:37:34.265 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'Long[]' value '[Ljava.lang.Long;@3d494fbf' to type 'Long[]'
contact-center_1  | 00:37:34.265 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a Long[]
contact-center_1  | 00:37:34.265 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.lang.Short;@133314b
contact-center_1  | 00:37:34.265 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'Short[]' value '[Ljava.lang.Short;@133314b' to type 'Short[]'
contact-center_1  | 00:37:34.286 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a Short[]
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.lang.String;@7cd84586
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'String[]' value '[Ljava.lang.String;@7cd84586' to type 'String[]'
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a String[]
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.lang.Class;@1b2c6ec2
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'Class[]' value '[Ljava.lang.Class;@1b2c6ec2' to type 'Class[]'
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a Class[]
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.util.Date;@70177ecd
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'Date[]' value '[Ljava.util.Date;@70177ecd' to type 'Date[]'
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a Date[]
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.util.Calendar;@66a29884
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'Calendar[]' value '[Ljava.util.Calendar;@66a29884' to type 'Calendar[]'
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a Calendar[]
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.io.File;@cc34f4d
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'java.io.File[]' value '[Ljava.io.File;@cc34f4d' to type 'java.io.File[]'
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter -     No conversion required, value is already a java.io.File[]
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Setting default value: [Ljava.sql.Date;@65b3120a
contact-center_1  | 00:37:34.287 [main] DEBUG org.apache.commons.beanutils.converters.ArrayConverter - Converting 'java.sql.Date[]' value '[Ljava.sql.Date;@65b3120a' to type 'java.sql.Date[]'

**Comment by leszz9527** [comment]
contact-center_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
contact-center_1  | status
contact-center_1  | nothing to rename

**Comment by hailiang-wang** [comment]
This is not an `ERROR`, the message type is WARN which means the server is running successfully. Don't bother it with WARN.
When `ERROR` log happens, it is a bug.

**Comment by leszz9527** [comment]
[root@localhost cskefu.osc]# docker ps
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                                                                                                                                                                NAMES
5e073e6174a2   chatopera/contact-center:develop   "./docker-entrypoint…"   37 minutes ago   Up 37 minutes   8030-8034/tcp, 8037-8050/tcp, 0.0.0.0:8035-8036->8035-8036/tcp, :::8035-8036->8035-8036/tcp                                                                          cskefu_contact-center_1
acf678027ae8   elasticsearch:2.4.6                "/docker-entrypoint.…"   37 minutes ago   Up 37 minutes   0.0.0.0:8039->9200/tcp, :::8039->9200/tcp, 0.0.0.0:8040->9300/tcp, :::8040->9300/tcp                                                                                 cskefu_elasticsearch_1
1c2e642a0efb   chatopera/activemq:5.14.3          "/app/run.sh"            37 minutes ago   Up 37 minutes   1883/tcp, 5672/tcp, 61614/tcp, 0.0.0.0:8051->8161/tcp, :::8051->8161/tcp, 0.0.0.0:8053->61613/tcp, :::8053->61613/tcp, 0.0.0.0:8052->61616/tcp, :::8052->61616/tcp   cskefu_activemq_1
5dd33daa8a15   chatopera/redis:5.0.5              "docker-entrypoint.s…"   37 minutes ago   Up 37 minutes   0.0.0.0:8041->6379/tcp, :::8041->6379/tcp                                                                                                                            cskefu_redis_1
865a32546987   chatopera/mysql:5.7                "docker-entrypoint.s…"   37 minutes ago   Up 37 minutes   33060/tcp, 0.0.0.0:8037->3306/tcp, :::8037->3306/tcp                                                                                                                 cskefu_mysql_1

没有nginx的容器吧？

**Comment by leszz9527** [comment]
contact-center_1  | ==================== Powered by Chatopera Inc. =================
contact-center_1  | 春松客服: 越是重视客户服务，越是好的企业 v7.0.0-SNAPSHOT build d803abe
contact-center_1  | 版权所有 © 北京华夏春松科技有限公司️ https://www.chatopera.com/
contact-center_1  | 商业许可授权联系商务顾问 https://dwz.chatopera.com/A51h6m
contact-center_1  | 春松客服博客专栏 https://blog.chatopera.com/
contact-center_1  | 
contact-center_1  | 第一次安装后，参考系统初始化文档，对系统进行初始化，再使用！！！
contact-center_1  | https://docs.chatopera.com/products/cskefu/initialization.html
contact-center_1  | 
contact-center_1  | 使用过程中，进行维护：备份、回复、升级等，参考文档
contact-center_1  | https://docs.chatopera.com/products/cskefu/osc/maintainence.html
contact-center_1  | 
contact-center_1  | 春松客服定制开发技能培训：春松客服大讲堂
contact-center_1  | https://docs.chatopera.com/products/cskefu/osc/training.html
contact-center_1  | 
contact-center_1  | 开源社区反馈建议& 提交 BUG
contact-center_1  | https://github.com/chatopera/cskefu/issues
contact-center_1  | 
contact-center_1  | 鼓励我们不断的优化春松客服，给春松客服点赞
contact-center_1  | https://github.com/chatopera/cskefu/stargazers
contact-center_1  | ----------------------------------------------------------------
contact-center_1  | 2021-10-31 00:38:07.049 WARN  o.h.id.UUIDHexGenerator - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead [localhost-startStop-1] 

日志到这里就不动了，我感觉服务并没有完全启动

**Comment by hailiang-wang** [comment]
Check out https://github.com/chatopera/cskefu/blob/osc/docker-compose.yml

```
docker-compose up -d nginx
```

**Comment by hailiang-wang** [comment]
注意最小资源的依赖，

https://docs.chatopera.com/products/cskefu/deploy.html

如果服务器资源少，启动会很慢。正常启动在 5 mins 之内。

**Comment by leszz9527** [comment]
好的，我资源确实不够，，我再找个环境部署下

**Comment by leszz9527** [comment]
从浏览器打开 http://YOUR_IP:CC_WEB_PORT/ 访问服务。 默认管理员账号： admin 密码： admin1234
这个可以登录了，，但是日志还是在哪个uuid warn那里不动了，，这个属于成功吗？

**Comment by hailiang-wang** [comment]
Find something like 

```
INFO  c.c.socketio.SocketIOServer - SocketIO server started at port: 8036 [nioEventLoopGroup-2-1]
INFO  com.chatopera.cc.Application - Started Application in 35.319 seconds (JVM running for 42.876) [main]
```

In the log.

If you can login from browser. Everything works fine.

**Comment by leszz9527** [comment]
我并没有发现这两行，但是浏览器是可以访问的。

**Comment by hailiang-wang** [comment]
查看 .env 文件，https://docs.chatopera.com/products/cskefu/deploy.html#%E9%85%8D%E7%BD%AE%E9%A1%B9

`LOG_LEVEL` 是 WARN 还是 INFO，以上提示在 INFO 时显示。

**Comment by leszz9527** [comment]
WARN

**Comment by leszz9527** [comment]
请问下，nginx的话需要单独写一个docker-compose.yml?

**Comment by leszz9527** [comment]
那我就不加nginx了，麻烦，外围还有nginx和cdn，，所以，应用服务器上不加会更好吧？

**Comment by hailiang-wang** [comment]
CDN 或 HTTPs 配置，在 Issues 中搜索。每个 Issue 关注一个问题。解决后就关闭。thanks.
