### ISSUE TITLE
修改对话框色调，发送按钮没有变色

### ISSUE THREAD

**Issue by jichoucc** [chatopera/cskefu#505]
## 现在行为
修改对话框色调，发送按钮没有变色
## 预期行为
发送按钮跟随对话框变色
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
请增加截图，thanks。

**Comment by hailiang-wang** [comment]
请问现在有什么进展吗？后来怎么处理的？
是访客端网页渠道的【发送】按钮吗？
