### ISSUE TITLE
这机器人怎么设置常见问题啊 

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#507]
Labels: 帮助， 创建者: 王海良
# 描述

来自 Chatopera智能客服-客户群02 （微信群或私聊）对话记录

`tech`: 用着挺爽的  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-11-16 21:40:13)*
`L`: 这机器人怎么设置常见问题啊  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-11-17 15:43:53)*
`L`: 就是那种一接入就弹出一些常见问题那种，不需要客户发什么内容  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-11-17 15:49:32)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

**Comment by hailiang-wang** [comment]
参考设置：热门问题问候语

https://docs.chatopera.com/products/cskefu/work-chatbot/message-types.html#%E7%83%AD%E9%97%A8%E9%97%AE%E9%A2%98%E9%97%AE%E5%80%99%E8%AF%AD
