### ISSUE TITLE
如何導入話術（或者常用語）的功能？

### ISSUE THREAD

**Issue by eva999999** [chatopera/cskefu#508]
## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
请添加截图，您希望在哪里使用常用语？

有没有阅读以下机器人客服的文档？

https://docs.chatopera.com/products/cskefu/work-chatbot/install.html

**Comment by eva999999** [comment]
> 请添加截图，您希望在哪里使用常用语？
> 
> 有没有阅读以下机器人客服的文档？
> 
> https://docs.chatopera.com/products/cskefu/work-chatbot/install.html

人工 客服工作台有常用语的快捷设置吗？

**Comment by hailiang-wang** [comment]
有，这个在春松客服中，就是知识库快捷：

https://docs.chatopera.com/products/cskefu/work-chatbot/bot-agent.html

![image](https://user-images.githubusercontent.com/3538629/142340810-b7ef1883-e75e-4129-b1de-01390b9dff2a.png)

**Comment by hailiang-wang** [comment]
现在已经导入了吗？有遇到新的问题吗？
