### ISSUE TITLE
串麦，和客服A里聊着聊着，突然就切到客服B了，客服没有转接

### ISSUE THREAD

**Issue by yangbailiang** [chatopera/cskefu#511]
## 现在行为
串麦，和客服A里聊着聊着，突然就切到客服B了，客服没有转接
## 预期行为
一次会话一直和同一个客服对接，除非转接
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
这个 BUG 会比较难复现，能不能再详细描述一下，客服 A 有做什么操作吗？
比如 客服 A 断网了？

**Comment by hailiang-wang** [comment]
访客有什么操作吗？

**Comment by hailiang-wang** [comment]
这个问题的出现，肯定是访客经过了重新分配了坐席。在坐席 A 不在线的情况下，才可能发生。但是也可能存在 BUG，所以，请详细说明一下坐席 A 的情况，如果坐席 A 的网络被中断了 20 秒以上，即使又恢复了网络，这时 TA 的访客也可能被分配到坐席 B。
