### ISSUE TITLE
关于帐号、角色、组织配置上的疑问及BUG反馈

### ISSUE THREAD

**Issue by RemyCHE** [chatopera/cskefu#513]
## 描述

1. 同个账号异地登入不会被强制登出，可以同时有2个地方登录同个号。（安全性问题）
2. 超级管理号无法看到其他普通管理号创建的帐号。 管理号之间无法看到彼此创建的新帐号。
3. 超级管理号在【用户账号】创建新用户时，创立在附属部门之下。此新账号不会在【用户账号】显示，也无法进行删除/编辑。
4. 透过第3点创立的新账号，超级管理员无法移除在【组织架构】移除部门 或 修改部门。
5. 超级管理员删除账号后，仍是处于登入后台状态。重新整理还是在登入后台的状态。
6. 超级管理号在【用户账号】创建新用户时，创立在根部门之下，也无法事后设置为其他附属部门之下
7. 企业聊天无法正常显示。提示如下
`Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Nov 23 18:10:21 CST 2021
There was an unexpected error (type=Internal Server Error, status=500).
Unable to find com.chatopera.cc.model.User with id 2c9380867d2d3211017d4bee85aa01ca; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.chatopera.cc.model.User with id 2c9380867d2d3211017d4bee85aa01cal `
## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
感谢，但是 Issue 追踪要每个独立的问题，都建立单独的 Issue，以上我看了，可以建立 7 个 Issue 进行追踪。
您能帮忙单独建立一下吗，有强关联的，彼此依赖的，可以放在一个 Issue 内。
您建立好了，我们进行处理，感谢！
