### ISSUE TITLE
好多jar包找不到，比如de.neuland.pug4j这些jar

### ISSUE THREAD

**Issue by zhengyuewen** [chatopera/cskefu#516]
## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
<html>
<body>
<div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">开发环境搭建参考文档：<a href="https://docs.chatopera.com/products/cskefu/osc/engineering.html" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://docs.chatopera.com/products/cskefu/osc/engineering.html&amp;source=gmail&amp;ust=1637821136253000&amp;usg=AOvVaw2HmxoBIYdmfaq4TolPanp9" style="color: rgb(17, 85, 204);">https://docs.<wbr>chatopera.com/products/cskefu/<wbr>osc/engineering.html</a></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">注意：</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">1. 机器的网络可以访问到：<a href="https://nexus.chatopera.com/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://nexus.chatopera.com/&amp;source=gmail&amp;ust=1637821136253000&amp;usg=AOvVaw0IrjByER1E3ACyJE7CAGRM" style="color: rgb(17, 85, 204);">https://nexus.<wbr>chatopera.com/</a><span> </span>打开这个 URL 可以看到 nexus 的页面。</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">2. 默认的 Repo 配置，没有被覆盖：<a href="https://github.com/chatopera/cskefu/blob/aec02346e4507614f0e42d3642f3d36272772b3f/contact-center/root/pom.xml#L381" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://github.com/chatopera/cskefu/blob/aec02346e4507614f0e42d3642f3d36272772b3f/contact-center/root/pom.xml%23L381&amp;source=gmail&amp;ust=1637821136253000&amp;usg=AOvVaw2DTQV7XXra1b-eHf4g0H7y" style="color: rgb(17, 85, 204);">https://github.com/<wbr>chatopera/cskefu/blob/<wbr>aec02346e4507614f0e42d3642f3d3<wbr>6272772b3f/contact-center/<wbr>root/pom.xml#L381</a></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br></div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">```</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

<repositories>
--
  | <repository>
  | <id>chatopera</id>
  | <name>Chatopera Inc.</name>
  | <url>https://nexus.chatopera.com/repository/maven-public</url>
  | <releases>
  | <enabled>true</enabled>
  | </releases>
  | <snapshots>
  | <enabled>true</enabled>
  | </snapshots>
  | </repository>
  | </repositories>

</div><div style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">```</div>
</body>
</html>

**Comment by hailiang-wang** [comment]
现在问题解决了吗？如果可以安装 jar 包了，请关闭一下 Issue，thanks.

**Comment by zhengyuewen** [comment]
> 现在问题解决了吗？如果可以安装 jar 包了，请关闭一下 Issue，thanks.

好的，谢谢
