### ISSUE TITLE
我这数据好像出问题了，可能是缓存导致的，我如果直接把redis清空，会有什么影响吗

### ISSUE THREAD

**Issue by Functional-Account** [chatopera/cskefu#517]
Labels: 帮助， 创建者: 王海良
# 描述

来自 Chatopera智能客服-客户群02 （微信群或私聊）对话记录

我这数据好像出问题了，可能是缓存导致的，我如果直接把redis清空，会有什么影响吗&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-11-24 09:06:34)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

**Comment by mukaiu** [comment]
清理后重启项目，不会有影响
