### ISSUE TITLE
网站渠道生成的访客访问链接无法作用

### ISSUE THREAD

**Issue by RemyCHE** [chatopera/cskefu#522]
## 描述

![image](https://user-images.githubusercontent.com/94896566/143809949-764b29ea-db5e-430a-9885-9b22fec2e78e.png)

![image](https://user-images.githubusercontent.com/94896566/143810607-908f8175-ad47-4a39-b1a4-b586ca7bfb30.png)

您好，在私有部署后，一开始并无照着以上流程进行系统初始化设置。后将所有部门、角色、帐号全数删除后，已按照上方正确流程进行系统初始化设置。

目前设置部门组织有三个层级，已在最高第一层级根部门按照系统初始化流程设置好帐号、角色/角色权限、组织。

但无论在最高第一层级根部门/第二层级子部门/第三层级子部门设置网站渠道生成的访客访问链接都无法作用——无法分配客服、客服端无客户进线、客户端亦无法发送信息。

因非技术人员出身，劳烦您用浅显易懂的方式解说要如何操作使用，感谢！

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by RemyCHE** [comment]
这边也劳烦回覆说明，谢谢

**Comment by hailiang-wang** [comment]
访客端打开网页渠道的截图，帮忙发一下！
在打开的访客端浏览器和坐席人员的浏览器中，使用 “右键”“Inspect/分析”查看 console log 日志，

![image](https://user-images.githubusercontent.com/3538629/143826729-686c3431-558d-41c9-861d-e58902df268b.png)

有无红色的日志。如果链接正常，会有如下类似的打印：


![image](https://user-images.githubusercontent.com/3538629/143826791-977d6a1f-e786-46cf-8b53-adfe8518bd8f.png)

**Comment by RemyCHE** [comment]
![image](https://user-images.githubusercontent.com/94896566/143827666-d1a5cdf0-2330-49f0-a2db-323e234a77cd.png)
Console 显示如截图，请问该如何处理？

**Comment by hailiang-wang** [comment]
socketio 连接失败了，是有使用 HTTPs 吗？

HTTPS 配置，参考：

https://github.com/chatopera/cskefu/issues/473

https://github.com/chatopera/cskefu/issues/414#issuecomment-790485168

这个需要你们工程师来看一下。

```
[IM] 初始化连接成功。
```

这个是正确的提示消息。

**Comment by RemyCHE** [comment]
好的，感谢说明。

**Comment by mukaiu** [comment]
@RemyCHE 提供一个可以访问的地址，我看看具体配置。

**Comment by RemyCHE** [comment]
> @RemyCHE 提供一个可以访问的地址，我看看具体配置。

请问是指访客端的链接吗？

**Comment by mukaiu** [comment]
客服端地址，账号等信息，在 客户群 里发个消息，我加你。

**Comment by RemyCHE** [comment]
> 客服端地址，账号等信息，在 客户群 里发个消息，我加你。

不好意思，这边要先取得上级的同意，明天再回覆您答复。

**Comment by mukaiu** [comment]
> > 客服端地址，账号等信息，在 客户群 里发个消息，我加你。
> 
> 不好意思，这边要先取得上级的同意，明天再回覆您答复。

👌

**Comment by RemyCHE** [comment]
您好，
更新后续，

> socketio 连接失败了，是有使用 HTTPs 吗？
> 
> HTTPS 配置，参考：
> 
> #473
> 
> [#414 (comment)](https://github.com/chatopera/cskefu/issues/414#issuecomment-790485168)
> 
> 这个需要你们工程师来看一下。
> 
> ```
> [IM] 初始化连接成功。
> ```
> 
> 这个是正确的提示消息。

您好，
更新后续，目前透过重新HTTPS 配置，访客端已可以顺利进线留言，客服坐席也顺利分配完成，可以看到访客留言。

但是客服坐席端无法发送留言，只能看到访客留言。
Console结果如附图，劳烦再说明应如何处理？ 感谢

![image](https://user-images.githubusercontent.com/94896566/144548839-a8ca9416-3040-4f46-a5d7-8cd42e048b5b.png)

**Comment by mukaiu** [comment]
和部署环境有关系，需访问你们系统后才能确定错误点

**Comment by RemyCHE** [comment]
![image](https://user-images.githubusercontent.com/94896566/144564944-22a86bda-d9a1-43e3-9260-5e71b9bb442f.png)


> 和部署环境有关系，需访问你们系统后才能确定错误点

您好，请问是直接加入此微信群私聊沟通后续吗？

**Comment by mukaiu** [comment]
@RemyCHE 对
