### ISSUE TITLE
已删除用户帐号的用户名无法再次创建使用

### ISSUE THREAD

**Issue by RemyCHE** [chatopera/cskefu#523]
## 描述

![image](https://user-images.githubusercontent.com/94896566/143812836-7c48d371-42bb-4954-9cbf-8a49dea64bc1.png)
![image](https://user-images.githubusercontent.com/94896566/143812850-433e1395-9d76-491b-9566-abf6d8497fb5.png)

您好，在私有部署后，一开始并无照着以上流程进行系统初始化设置。后将所有部门、角色、帐号全数删除后，已按照上方正确流程进行系统初始化设置。

第一次全数删除的用户账号，有些是在根部门用户账号直接删除，有些是在直接删除子部门（无呈列在根部门用户帐号）。

现用同样用户名创建帐号时，会提示用户名已使用，无法创建。请问要如何处理？

因非技术人员出身，劳烦您用浅显易懂的方式解说要如何操作使用，感谢！

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
用的软件版本是哪个？
可以用最新的试试吗？

获得版本的方法：

## 第一步
![image](https://user-images.githubusercontent.com/3538629/143822152-cad2de44-a890-4ba5-b562-5cebdb62afc9.png)

## 第二步
![image](https://user-images.githubusercontent.com/3538629/143822174-2e0fd7dd-de2d-4d71-afdb-33b72dc1eab0.png)

**Comment by RemyCHE** [comment]
您好，
版本如附图
![image](https://user-images.githubusercontent.com/94896566/143822308-a07cfc7d-6974-4016-98bc-0451d0230a8b.png)
20211116.035635.d803abe

劳烦再协助告知该如何处理，感谢您。

**Comment by hailiang-wang** [comment]
可能是 BUG，因为这些数据在【删除】的时候，可能只是做了【标记】，不显示和使用而已，在数据库中还有，并没有真正的删除。

您说的一样的账户，是指【用户名】一样吗？

![image](https://user-images.githubusercontent.com/3538629/143822728-91e6ecbe-bdae-4729-82e1-4f7b04c31128.png)

**Comment by RemyCHE** [comment]
是的，没错。

请问要如何处理呢？

**Comment by hailiang-wang** [comment]
用户名作为唯一的标识，已经和之前用户的数据进行了关联。新的用户，也不能用之前的用户名。但是可以用一样的【姓名】。
有两种方案：
1）重新部署系统；
2）新建的用户的用户名修改一下。

这里有数据关联的原因：
1）用户名唯一；
2）删除的用户，数据不删除。

设计如此，这个设计也是合理的。用户名一旦设置不能变更，也是唯一的。

**Comment by hailiang-wang** [comment]
重新部署系统使用脚本：

```
cd cskefu
./scripts/flush.sh
```

就会刷新，**注意此时历史数据将会丢失**!!!

**Comment by RemyCHE** [comment]
请问
1）重新部属系统》》是指重新删除全数所有部门、角色、帐号，再重新系统初始化部署吗？

另外需要补充说明，是只有少数用户名不能重新创建使用，所以用户名唯一性有待商榷。

**Comment by RemyCHE** [comment]
> 重新部署系统使用脚本：
> 
> ```
> cd cskefu
> ./scripts/flush.sh
> ```
> 
> 就会刷新，**注意此时历史数据将会丢失**!!!

好的，感谢说明，谢谢！

**Comment by hailiang-wang** [comment]
> 请问 1）重新部属系统》》是指重新删除全数所有部门、角色、帐号，再重新系统初始化部署吗？
> 
> 另外需要补充说明，是只有少数用户名不能重新创建使用，所以用户名唯一性有待商榷。

**是只有少数用户名不能重新创建使用** 这些账号有什么特点呢？是不是这些账号在另外一个组织机构下了？

**Comment by hailiang-wang** [comment]
春松客服的备份，升级，恢复等，参考：

https://docs.chatopera.com/products/cskefu/osc/maintainence.html

春松客服大讲堂，也有相关的介绍：
https://chatopera.blog.csdn.net/article/details/121599407

**Comment by RemyCHE** [comment]
> > 请问 1）重新部属系统》》是指重新删除全数所有部门、角色、帐号，再重新系统初始化部署吗？
> > 另外需要补充说明，是只有少数用户名不能重新创建使用，所以用户名唯一性有待商榷。
> 
> **是只有少数用户名不能重新创建使用** 这些账号有什么特点呢？是不是这些账号在另外一个组织机构下了？


目前观察是只有直接删除子部门（无呈列在根部门用户帐号），没有直接在『用户账号』删除的用户名不能重新创建使用

**Comment by RemyCHE** [comment]
复现状况如下，举例而言

1.使用超级管理员帐号登入后，至右上角『系统』-『用户和组』-『组织机构』直接「删除部门」
![image](https://user-images.githubusercontent.com/94896566/143842006-777adab3-5496-413a-97b0-2368061e1ddc.png)
刚刚删除的『游戏客服』部门所属的账号：CS001 CS002
是不会出现在『用户账号』的列表中
![image](https://user-images.githubusercontent.com/94896566/143841734-98015ff1-bd43-42ca-9bf4-be9c9fbda0ff.png)

2. 再次在『用户账号』创建同样用户名在第一层级根部门时，会显示用户名已存在，无法创建用户。
![image](https://user-images.githubusercontent.com/94896566/143842794-d7bd67f8-3afa-408c-91d0-b04e6d073e1e.png)

**Comment by mukaiu** [comment]
@RemyCHE 上面操作是删除组织，并未删除用户，最新版本已添加删除提示。CS001 CS002 可以去数据库中直接删除上述用户，或重建数据库。
