### ISSUE TITLE
请问可以通过配置修改把logo修改一下么？

### ISSUE THREAD

**Issue by fywang2** [chatopera/cskefu#530]
## 概述

请问可以通过配置修改把logo修改一下么？
## 理想解决方案
私有化部署或公有云租户方式，最终用户希望访问系统可以看到租户所在公司的LOGO，这样用户体验更好一些。
<img width="690" alt="5c0360bf7dd6b74517470f451cd9795" src="https://user-images.githubusercontent.com/12983315/144343507-7e65cff7-f61b-44f1-a711-f9ce66147e2f.png">

## 来自

- 行业：
- 公司/团队 官网：

## Open Source for the World by Chatopera 

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/42383104-da925942-8168-11e8-8195-868d5fcec170.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
使用系统超级管理员，进入系统管理-渠道管理。

在目标网站渠道，点击【接入】。

找到 LOGO 进行上传。

![image](https://user-images.githubusercontent.com/3538629/144343826-7d48afb4-b553-4bdc-89b6-1307319b8370.png)
