### ISSUE TITLE
按照文档添加天气查询功能的时候，点击保存之后，长时间没有反馈，设计器卡死

### ISSUE THREAD

**Issue by Tucker29** [chatopera/cskefu#553]
## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
重启多轮对话设计器后，

1. 可以对话吗？
2. 保存还是卡吗？

**Comment by Tucker29** [comment]
重启多轮对话设计器后，之前保存的脚本和函数会消失，需要重新输入脚本和函数，然后点保存之后，又卡死

**Comment by hailiang-wang** [comment]
请帮忙提供调试日志：

1）打开调试控制台

![image](https://user-images.githubusercontent.com/3538629/145562736-62a53d3c-49ca-4212-bcae-3834db111240.png)


2）查看 console
![image](https://user-images.githubusercontent.com/3538629/145562827-7c5fbe31-9d95-4811-be3a-a8c8129f801d.png)

3）在多轮对话设计器中，点击【保存】

这时，如果卡死，在 console 中将会有日志信息。

请将日志信息，尤其是红色的日志，截图。
