### ISSUE TITLE
有没有离线消息的功能?客服上线就绪后在分配到客服

### ISSUE THREAD

**Issue by lokywang** [chatopera/cskefu#554]
## 描述
有没有离线消息的功能?客服上线就绪后在分配到客服

## 功能
有没有离线消息的功能?客服上线就绪后在分配到客服

## 操作系统

- [x] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
【客服上线就绪后在分配到客服】，这是说，访客可以留言吗？请用角色的进行表述，比如访客怎么操作，坐席怎么操作。

**Comment by lokywang** [comment]
> 【客服上线后就在发到客服了】，这是说，访客可以留言吗？请用角色的进行表述，比如访客怎么操作，坐席怎么操作。

当无人工坐席在线,客户能发送消息,等到有人工坐席时,积累的客服消息能分配到坐席上,访客再次开打时,能看到消息回复

**Comment by mukaiu** [comment]
不支持，欢迎 PR
