### ISSUE TITLE
能不能进行多人会话，比如拉个群组群聊的功能 ？

### ISSUE THREAD

**Issue by michael-china** [chatopera/cskefu#555]
能不能进行多人会话，比如拉个群组群聊的功能 ？

**Comment by hailiang-wang** [comment]
支持，使用【企业聊天】模块。

## 打开企业聊天
![image](https://user-images.githubusercontent.com/3538629/145943883-494bf91c-7b6a-4755-8a90-2e3e365b1c01.png)

## 管理企业聊天对话
![image](https://user-images.githubusercontent.com/3538629/145943849-23bec504-373e-40ce-9514-62289c265b73.png)

**Comment by hailiang-wang** [comment]
企业聊天，默认就是开启的。不用的话，还可以关闭。

超级管理员，进入系统设置

![image](https://user-images.githubusercontent.com/3538629/145944046-bd029332-2c02-45bb-8ce6-dec86043ced6.png)
