### ISSUE TITLE
每次部署后,第一次网页打开慢,是因为tomcat要转换pug的问题吗?

### ISSUE THREAD

**Issue by lokywang** [chatopera/cskefu#559]
## 描述
每次部署后,第一次网页打开慢,是因为tomcat要转换pug的问题吗?

## 功能
每次部署后,第一次网页打开慢,是因为tomcat要转换pug的问题吗?

**Comment by hailiang-wang** [comment]
所谓慢，是怎么个慢法？
第一次打开页面要多久？第二次打开要多久？

服务机器的硬件配置是什么？
部署方式是何种，使用了我们的推荐的 Docker 容器吗？

**Comment by lokywang** [comment]
> 所谓慢，是怎么个慢法？ 第一次打开页面要多久？第二次打开要多久？
> 
> 服务机器的硬件配置是什么？ 部署方式是何种，使用了我们的推荐的 Docker 容器吗？

服务器配置是8h32g,部署当时docker-compose,每次重新部署后，打开每一个没有打开过的页面，基本会卡顿3到4秒左右，关闭或刷新，第二次打开时，基本秒开。是因为缓存机制，第一次打开时需要缓存吗？

**Comment by hailiang-wang** [comment]
PUGJS 的缓存不会导致延迟这么大，这个缓存可能是来自于其他方面。
比如 Session 中会加载这个登录用户的组织机构等信息，这个地方看你们组织机构的设计。最可靠的是在后端的打一些日志。
LoginController 中，尤其是这个类。

**Comment by hailiang-wang** [comment]
有什么发现么？后来打开网页还会慢吗？
解决了吗？
@lokywang 

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by lokywang** [comment]
还没有发现具体问题，猜测是单线程编译pug问题，后续再观察观察，每次重新部署后都会出现类似问题。

**Comment by hailiang-wang** [comment]
总之，这个问题是初始化信息导致，解决方案为部署后，自动的进一步的初始化。
这个点不影响使用。
