### ISSUE TITLE
请帮忙看下为什么PC端客服无法想用户发送消息？

### ISSUE THREAD

**Issue by fjfox2426** [chatopera/cskefu#560]
## 描述
微信小程序端可以发送消息到客服，并显示在坐席上。但客服却无法发送消息给用户，在浏览器开发者模式下发现PC端的websock连接的地址是127.0.0.1

## 操作系统

- [x] macOS or Mac OSX
- [ ] Windows
- [ centos ] Linux(Debian, CentOS, Ubuntu, etc.)

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by mukaiu** [comment]
客服发送消息，截图示意一下，包含 console 信息

**Comment by fjfox2426** [comment]
![image](https://user-images.githubusercontent.com/45957031/146784188-c901d743-9642-4b51-803d-8d2f4e2d9e25.png)

**Comment by fjfox2426** [comment]
![image](https://user-images.githubusercontent.com/45957031/146784324-24728af4-480f-4ca4-9831-de55c69b53e7.png)

**Comment by hailiang-wang** [comment]
# 春松客服支持微信小程序的开发企业微信群
面向使用微信小程序原生的方式，GitHub 地址： https://github.com/chatopera/cskefu-wxapp

![image](https://user-images.githubusercontent.com/3538629/146856223-57eaa9f9-f584-4d46-a560-3fc28d55e9a9.png)

**Comment by mukaiu** [comment]
反向代理配置问题，参考 https://github.com/chatopera/cskefu/issues/414 调整。
先保证 HTTP 访问正常

**Comment by fjfox2426** [comment]
> # 春松客服支持微信小程序的开发企业微信群
> 面向使用微信小程序原生的方式，GitHub 地址： https://github.com/chatopera/cskefu-wxapp
> 
> ![image](https://user-images.githubusercontent.com/3538629/146856223-57eaa9f9-f584-4d46-a560-3fc28d55e9a9.png)

用的就是这个小程序。主要是PC端的配置问题，我试下配置下代理，不知道行不行

**Comment by fjfox2426** [comment]
> 配置 [HTTPs](https://chatopera.blog.csdn.net/article/details/105820829) 文档中，对 `CC_SOCKET_PORT` 环境变量的使用，描述的不对，或需要修改 docker-compose 增加一个变量。
> 
> ![image](https://user-images.githubusercontent.com/3538629/109945871-a4a39780-7d12-11eb-839b-3cdc91faca2a.png)
> 
> 可能的解决方案
> 
> https://github.com/chatopera/cskefu/blob/e04ace620f99a32186cf6b524f4bf252cb377740/docker-compose.yml#L21
> 
> 此处的 `CC_SOCKET_PORT` 变量名改为 `CC_SOCKET_OS_PORT`, 默认为 8036，并且在不清楚代码细节的情况下，不建议修改。

按这个配置修改，成功了。
