### ISSUE TITLE
缺失jar包

### ISSUE THREAD

**Issue by live-in-the-moment** [chatopera/cskefu#566]
通过maven 有些jar包无法下载 
1. com.chatopera.compose4j
2. com.chatopera.bot
3. de.neuland-bfi
4. 如上jar包无法通过maven 下载

**Comment by hailiang-wang** [comment]
Chatopera nexus 服务正常，

https://nexus.chatopera.com/

请确保你的机器可以打开 Chatopera nexus 的地址。

设置 maven settings 参考开发环境搭建文档。

[配置 maven](https://docs.chatopera.com/products/cskefu/osc/engineering.html#%E9%85%8D%E7%BD%AE-maven)

另外，在 contact-center 源码中，已经默认配置好了，见 https://github.com/chatopera/cskefu/blob/4ab3cb83b5781e5a96563db08752af0e12121bec/contact-center/root/pom.xml#L382

所以，你说的情况可能是：

1）网络连接不到 Chatopera Nexus

2) 默认的 Maven repo 设置被覆盖了，没有使用 chatopera repo. 


Maven 基础知识可参考春松客服大讲堂，具体章节见下。

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by hailiang-wang** [comment]
duplicated with #567
