### ISSUE TITLE
无法找到  de.neuland-bfi 下的spring-pug4j 的 2.0.0-alpha-4-SNAPSHOT 版本

### ISSUE THREAD

**Issue by live-in-the-moment** [chatopera/cskefu#567]
在 https://nexus.chatopera.com/ 内找不到 spring-pug4j 的 2.0.0-alpha-4-SNAPSHOT 版本

**Comment by hailiang-wang** [comment]
请提供一下报错的信息，截图或日志。

**Comment by live-in-the-moment** [comment]
Could not find artifact de.neuland-bfi:spring-pug4j:pom:2.0.0-alpha-4-SNAPSHOT in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public)
![QQ截图20211228111744](https://user-images.githubusercontent.com/62800943/147524305-4d9fb352-5f42-4a6f-b1dd-4c33ef9fa413.png)

![QQ截图20211228111826](https://user-images.githubusercontent.com/62800943/147524357-5332ae73-cba2-471a-88f7-842e2a11737b.png)

**Comment by hailiang-wang** [comment]
从报错信息看，您的 maven 配置的 repo 没有使用 Chatopera Nexus, 而是 Aliyun 的 repo。

![image](https://user-images.githubusercontent.com/3538629/147526025-8c8d0b92-6f66-4121-b1e9-1b4207315b7f.png)

按照这里的描述，https://github.com/chatopera/cskefu/issues/566#issuecomment-1001518390

需要您配置 maven 指向 Chatopera Nexus, 其中， Chatopera Nexus 也是代理了 Aliyun repo 服务，所以没有问题，之前的引用不会有冲突。

de.neuland-bfi 下的spring-pug4j 的 2.0.0-alpha-4-SNAPSHOT  是在 Chatopera Nexus 的。


![image](https://user-images.githubusercontent.com/3538629/147526159-16ad5557-63f9-481b-84ea-8b812654455d.png)

请一定确保，使用 Chatopera Nexus 的 Maven Repo 服务。

**Comment by hailiang-wang** [comment]
以下的两个课程，您看一下。

https://chatopera.blog.csdn.net/article/details/121599407

![image](https://user-images.githubusercontent.com/3538629/147527675-d30d952c-c879-42ff-9c95-8f57b06f4446.png)

对 maven 的配置，在 USER/.m2/settings.xml 以及在项目 pom.xml，还有在 IDEA 中都可以。它们的优先级，以及在运行时，究竟使用了哪个 Repo，Repo 有哪些类型，需要做好学习。
