### ISSUE TITLE
配置域名后 智能客服不能使用, 用ip访问是可以的

### ISSUE THREAD

**Issue by lovealo** [chatopera/cskefu#569]
## 描述
配置域名后 智能客服不能使用, 用ip访问是可以的

## 功能
配置域名后 智能客服不能使用, 用ip访问是可以的

## 操作系统

- [ Linux]
![18](https://user-images.githubusercontent.com/17755546/147534702-5c55e82c-7ae7-4036-ad09-e1589debb698.png)

**Comment by lovealo** [comment]
使用ip地址是ok的, 下面是ip访问的截图
![Uploading 181.png…]()

**Comment by hailiang-wang** [comment]
## 配置并使用了 HTTPs
参考 https 配置：https://chatopera.blog.csdn.net/article/details/105820829
如果 https 配置遇到问题，参考 https://github.com/chatopera/cskefu/issues/414#issuecomment-790485168

## 没有配置并使用了 HTTPs

防火墙是否开启 8036，在云服务器上，也有安全策略，安群组。
需要允许 8035, 8036 上行。

**Comment by hailiang-wang** [comment]
现在问题解决了吗？

**Comment by lovealo** [comment]
已经解决  `         location / {
        # 传递请求头
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://192.168.101.173:8035;
    }

    # 代理WebScoket
    location /socket.io {
    # WebScoket 支持
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://192.168.101.173:8036;
    }

}
server{
   listen 8036;
   server_name kf.51fgz.cn;
   location /socket.io {
    # WebScoket 支持
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_pass http://192.168.101.173:8036;
    }

}`
