### ISSUE TITLE
Too many bugs, the online customer number can't work, can't assign customer

### ISSUE THREAD

**Issue by zhangchunsheng** [chatopera/cskefu#570]
![image](https://user-images.githubusercontent.com/831839/147557994-51fd0813-7202-47ab-8c00-6899f52b3535.png)

**Comment by hailiang-wang** [comment]
Please add more details. 

The initial work should be done for an agent account, only after the agent has proper roles, organs, the agent account can be assigned.

Read this doc for more information.
https://docs.chatopera.com/products/cskefu/initialization.html


---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by zhangchunsheng** [comment]
There are 3 agent, no one can be assigned. but if switch the below button, and change it back, the agent can be assigned. That's too bad, waste coder's time.

You should test the code, not suppose that coder haven't config.

![image](https://user-images.githubusercontent.com/831839/147626497-e4b3ba7c-e000-491d-84fe-057a14c73840.png)

**Comment by hailiang-wang** [comment]
thanks, how did you setup CSKeFu? with our docker image? or run with a dev machine? Is there any errors in the console? 
How about the connection of socket.io?

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
