### ISSUE TITLE
PHP SDK 多轮兑换检索部分意图不能识别

### ISSUE THREAD

**Issue by shangdev** [chatopera/cskefu#575]
## 现在行为
在chatopera控制台创建了2个意图：

1、查询规格文件（用户说法：规格文件、搜索规格文件、货品规格文件、查询规格文件）
2、查询采购进度（采购进度、物料采购进度、物料进度）

通过 SDK API 检索多轮对话：
```
$chatbot = new Chatbot('xxx', 'xxx');
$response = $chatbot->command('POST', '/conversation/query', [
    "fromUserId"   => 'xxx',
    "textMessage" => 'xxx',
]);
```

当传递意图用户说法：规格文件时，能识别并返回追问；
当传递意图说法：采购进度时，返回兜底回答。

## 预期行为
识别设定的意图，返回对应话术。

## 代码版本
PHP SDK最新版：https://github.com/chatopera/chatopera-php-sdk

**Comment by hailiang-wang** [comment]
这两个意图，在多轮对话设计器中，都关联了意图匹配器吗？

**Comment by hailiang-wang** [comment]
另外，在集成到意图匹配器之前，有没有在“测试对话”中，进行测试？能不能匹配到呢？

![image](https://user-images.githubusercontent.com/3538629/147798875-c0b896e0-ab96-448c-87bb-41708d0fe22b.png)

**Comment by shangdev** [comment]
未识别的那个没关联意图匹配器，新建意图匹配后，可以识别到 了。。，这么看来 是每个意图都得新建一个意图匹配了？

**Comment by hailiang-wang** [comment]
意图识别模块是标注和训练意图的；多轮对话脚本是处理意图的 - 获得意图识别结果，并通过函数进行下一步操作。
具体参考：

https://docs.chatopera.com/products/chatbot-platform/howto-guides/conv-gambit-intent.html

这样保证服务达到：Low code 和 Server Less 的效果。
设计就是这样。

**Comment by hailiang-wang** [comment]
通过入门教程，大约 40mins，掌握 Chatopera 机器人平台使用。

https://docs.chatopera.com/products/chatbot-platform/tutorials/index.html

进阶使用，参考文档中心：
https://docs.chatopera.com/products/chatbot-platform/howto-guides/index.html

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
