### ISSUE TITLE
客服系统中机器人回复匹配有多项选择时，对话框不能点匹配的超链接或者序号回复

### ISSUE THREAD

**Issue by Happy5** [chatopera/cskefu#579]
# 描述
客服系统中机器人回复匹配有多项选择时，对话框不能点匹配的超链接或者序号回复，如
## 现在行为
![4963051772c51fa28c4f35b0c9fe377](https://user-images.githubusercontent.com/53087368/148543451-cf5e48a1-90df-4c01-aa1d-c43a891665d6.png)
## 预期行为
当客服系统使用机器人回复时，如果匹配有多项选择，可回复序号或者点击超链接进行回复，从而获得期望的选项

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by hailiang-wang** [comment]
此处需要支持：将 FAQ 的建议列表，展示为 faq_hot_list 那种形式，

https://docs.chatopera.com/products/cskefu/work-chatbot/message-types.html#%E7%83%AD%E9%97%A8%E9%97%AE%E9%A2%98%E9%97%AE%E5%80%99%E8%AF%AD

![qIVibaLpRA](https://user-images.githubusercontent.com/3538629/148547952-619e1609-9538-410b-aefd-13e97fa1e13f.png)

**Comment by Happy5** [comment]
邮件已收到，我会尽快回复

**Comment by Happy5** [comment]
> 将 FAQ 的建议列表，展示为 faq_hot_list 那种形式，

每太明白，faq_hot_list 不是多轮会话的内容吗？ 机器人知识库有很多的问题，那每个问题都要设计几个多轮会话么，因为我看到多轮会话是需要对应设计一个函数的

**Comment by mukaiu** [comment]
@Happy5 支持 点击超链接进行回复，不支持直接回复序号

**Comment by Happy5** [comment]
邮件已收到，我会尽快回复
