### ISSUE TITLE
客服系统采用机器人回复时，其结果与 Chatopera云服务直接测试的结果不同

### ISSUE THREAD

**Issue by Happy5** [chatopera/cskefu#580]
# 描述
客服系统采用机器人回复时，其结果与 Chatopera云服务直接测试的结果不同
## 现在行为
1：机器人直接测试结果
![image](https://user-images.githubusercontent.com/53087368/148545420-bd7eb2c2-3b8a-4458-b15d-6739684a32ca.png)
2：客服系统对接机器人的直接测试结果
![image](https://user-images.githubusercontent.com/53087368/148545530-5e720ed5-82fc-457b-9b46-02b86231a150.png)

# 环境

* 代码版本:
Git commit hash (`git rev-parse HEAD`)

**Comment by mukaiu** [comment]
![image](https://user-images.githubusercontent.com/7746790/151518697-f6223563-b24e-411c-aa1a-a27cbacba948.png)

@Happy5 ”这是你想要的问题吗“ 是 FAQ ”Jmeter“ 的答案。

春松客服中使用的是 "多轮对话"，使用多轮对话再次测试
![image](https://user-images.githubusercontent.com/7746790/151519001-b6d62db5-e8eb-4d5e-948a-1881ccfa1653.png)
