### ISSUE TITLE
桌面软件话术助手无法滚动智能回复内容，搜索某些词时报ID或密钥错误，

### ISSUE THREAD

**Issue by Happy5** [chatopera/cskefu#584]
## 现在行为
桌面软件话术助手无法滚动智能回复内容，搜索某些词时报ID或密钥错误，

https://user-images.githubusercontent.com/53087368/149148258-ef9d67c4-e701-49fa-8fc3-d39decb53c05.mp4

**Comment by mukaiu** [comment]
间歇性 报ID或密钥错误，是系统时间和服务器时间相差过大，同步下系统时间再试

**Comment by Happy5** [comment]
> 间歇性 报ID或密钥错误，是系统时间和服务器时间相差过大，同步下系统时间再试

时间是同步的，仅搜索某些特定词时会显示ID或密钥错误，而大部分词的搜索是正常的，详见视频

另外：桌面软件话术助手搜索后，有多条智能回复内容无法滚动
