### ISSUE TITLE
关于分支选择

### ISSUE THREAD

**Issue by VSUF-dev** [chatopera/cskefu#585]
您好！
我想要前端是html实现的，发现master等三个版本前端是html实现，但是其最近的更新都是在两三年前。如果我选择master分支，与最新的osc分支功能上的差别很大吗？

**Comment by hailiang-wang** [comment]
master 分支不维护了，osc 分支是维护的。

**Comment by hailiang-wang** [comment]
HTML 的代码已经达到了不可维护的状态，业务太复杂！
使用 pugjs 的代码质量非常高，具体入门使用参考：

https://blog.csdn.net/samurais/article/details/114576611

可以快速掌握春松客服的前端开发。

---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
