### ISSUE TITLE
https配置，websocket端口配置

### ISSUE THREAD

**Issue by jichoucc** [chatopera/cskefu#589]
## 描述

![image](https://user-images.githubusercontent.com/87190214/150101696-a286f993-50c2-4020-ad3c-ee145a4aa1a1.png)
这个websocket一直走其它端口，怎么配啊，.env、docker-compose 里面都没有，现在https用不了
## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
是希望它走 443 端口吗？

参考：

https://github.com/chatopera/cskefu/issues/414

**Comment by jichoucc** [comment]
好的，晚点我试试

**Comment by jichoucc** [comment]
> 是希望它走 443 端口吗？
> 
> 参考： [#414 (comment)](https://github.com/chatopera/cskefu/issues/414#issuecomment-790480953)
> 
> #414

好的，晚点我试试

**Comment by hailiang-wang** [comment]
现在可以了吗？#414 中的方案可以吗？

**Comment by hailiang-wang** [comment]
升级春松客服到最新版本验证，升级方法见：
https://docs.chatopera.com/products/cskefu/osc/maintainence.html
---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by hailiang-wang** [comment]
@all-contributors please add @jichoucc  for bug, test
