### ISSUE TITLE
报错 o.h.id.UUIDHexGenerator - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead [localhost-startStop-1]

### ISSUE THREAD

**Issue by shuhaoSCode** [chatopera/cskefu#594]
## 描述
o.h.id.UUIDHexGenerator - HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead [localhost-startStop-1] 

docker启动报这个错 不知道什么原因

## 操作系统

- [ ] macOS or Mac OS 12.2

## 代码版本
最新代码

**Comment by hailiang-wang** [comment]
这个不是报错，根据你的服务器资源，应用会在这个消息出现后的几分钟内完成启动。
资源配置参考：
https://docs.chatopera.com/products/cskefu/deploy.html


---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by hailiang-wang** [comment]
这个日志前面是有提示的：warning。
报错是 error。
