### ISSUE TITLE
chatopera云服务新建机器人利用模板导入问题时，扩展问题无法导入成功

### ISSUE THREAD

**Issue by Happy5** [chatopera/cskefu#595]
chatopera云服务新建机器人利用模板导入问题时，扩展问题无法导入成功

**Comment by hailiang-wang** [comment]
请帮忙上传一个您用的模板 excel 文件，感谢！
---
**请使用以下工具提升沟通效率**

* 工单管理： https://github.com/chatopera/cskefu/issues
* 文档中心：https://docs.chatopera.com/
* 商务洽谈：https://www.chatopera.com/mail.html

**春松客服大讲堂**

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)

**Comment by Happy5** [comment]
[](url)> ## 请帮忙上传一个您用的模板 excel 文件，感谢！
> **请使用以下工具提升沟通效率**
> 
> * 工单管理： https://github.com/chatopera/cskefu/issues
> * 文档中心：https://docs.chatopera.com/
> * 商务洽谈：https://www.chatopera.com/mail.html
> 
> **春松客服大讲堂**
> 
> [](https://chatopera.blog.csdn.net/article/details/121599407)
[知识库模版 - 1.xlsx](https://github.com/chatopera/cskefu/files/8013063/-.1.xlsx)

**Comment by hailiang-wang** [comment]
该问题可以复现，使用导入excel模板也是无法得到扩展问。该问题同样也发生在导入 json 格式文件，扩展问同样没有被创建出来。
其他字段在两个格式中还是正常的。

**Comment by Happy5** [comment]
> 该问题可以复现，使用导入excel模板也是无法得到扩展问。该问题同样也发生在导入 json 格式文件，扩展问同样没有被创建出来。
> 其他字段在两个格式中还是正常的。

好滴，请问什么时候可以更新呢?

**Comment by hailiang-wang** [comment]
开始看了，具体的时间 @mukaiu 评估后在告知。

**Comment by mukaiu** [comment]
@Happy5 已更新，再导入试试.

**Comment by Happy5** [comment]
> 已更新，再导入试试.

测试了下，确认没有问题了
