### ISSUE TITLE
nginx配置反向代理出现了502 

### ISSUE THREAD

**Issue by vicviz** [chatopera/cskefu#613]
## 描述
我参考了这个文章：https://blog.csdn.net/samurais/article/details/105820829

http://{我的ip}:8035正常，我想配置反向代理从而加上域名，但是使用nginx出错了。

在我的Nginx上配置好了:
server {
    listen       80;
    listen       [::]:80;
    server_name  _;
    root /usr/share/nginx/html;
    client_max_body_size 100M;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://contact-center:8035;
    }

    location /socket.io {
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_pass http://contact-center:8036;
    }
}

1. 请问一下是否有完整的nginx的/etc/nginx/nginx.conf配置代码可以贴出来参考一下？

## 操作系统

- [ ] Linux(CentOS)

## 代码版本
HEAD

**Comment by vicviz** [comment]
我的/etc/hosts中，加过127.0.0.1 contact-center的。
curl 127.0.0.1:8035也没有问题。

**Comment by vicviz** [comment]
seLinux的问题，关了就好了

**Comment by hailiang-wang** [comment]
感谢您反馈并在解决后给与解答！
