### ISSUE TITLE
centos使用源码编译的如何设置CC_SOCKET_PORT=443 使用环境变量么

### ISSUE THREAD

**Issue by 609685846** [chatopera/cskefu#620]
## 描述
centos使用源码编译的如何设置CC_SOCKET_PORT=443 使用环境变量么

## 功能
centos使用源码编译的如何设置CC_SOCKET_PORT=443 使用环境变量么

## 操作系统

centos

## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by 609685846** [comment]
cs.im.server.ssl.port=443

**Comment by hailiang-wang** [comment]
所有环境变量参考配置文件：

https://github.com/chatopera/cskefu/blob/osc/contact-center/app/src/main/resources/application.properties

配置文件和环境变量的映射方式，参考：

[环境变量和application.properties的映射](https://docs.chatopera.com/products/cskefu/osc/engineering.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)

**Comment by hailiang-wang** [comment]
推荐使用 Ubuntu，Ubuntu 对云服务更友好。
