### ISSUE TITLE
怎么获取聊天记录

### ISSUE THREAD

**Issue by yyget** [chatopera/cskefu#624]
## 概述

请问咱们可以导出聊天记录吗
为什么我用admin登录mysql看不到春松的数据库
## 理想解决方案
是不是可以在网页端导出聊天记录
增加聊天记录的统计功能
## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by yyget** [comment]
找到了，用root用户登录在cosinee，uk_chat_message

**Comment by hailiang-wang** [comment]
观看春松客服大讲堂，了解定制化开发。

**春松客服大讲堂**
https://blog.csdn.net/samurais/article/details/121599407

[https://chatopera.blog.csdn.net/article/details/121599407](https://chatopera.blog.csdn.net/article/details/121599407)
