### ISSUE TITLE
春松客服贡献者 / CSKEFU CONTRIBUTORS

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/cskefu#627]
Add more CONTRIBUTORS info in README.

https://allcontributors.org/docs/en/bot/usage

```
@all-contributors please add @<username> for <contributions>
```

Types 

https://allcontributors.org/docs/en/emoji-key

**Comment by hailiang-wang** [comment]
@all-contributors please add @mukaiu, @hailiang-wang, @luruiGit, @shih945 as developers

**Comment by hailiang-wang** [comment]
https://github.com/all-contributors please add @mukaiu, @hailiang-wang, @luruiGit, @shih945 for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @mukaiu, @hailiang-wang, @luruiGit, @shih945 for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @mukaiu for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @hailiang-wang  for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @shih945  for code
@all-contributors please add @luruiGit for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @shih945 for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @luruiGit for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @shih945 for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @enze5088 for code

**Comment by hailiang-wang** [comment]
@all-contributors  please add  @DevDengChao for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @kylezhang for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @xianliwang for video, test

**Comment by hailiang-wang** [comment]
@all-contributors please add @youkefu for code, test, business, design

**Comment by hailiang-wang** [comment]
@all-contributors please add @always-China for code

**Comment by Functional-Account** [comment]
@hailiang-wang 贡献者 LIST 备份

**Comment by Functional-Account** [comment]
@hailiang-wang FETCH TEST

**Comment by Functional-Account** [comment]
FETCH TEST 3

**Comment by Functional-Account** [comment]
FETCH TEST 7

**Comment by hailiang-wang** [comment]
@all-contributors please add @xiaobo9 for code

**Comment by hailiang-wang** [comment]
@all-contributors please add @xiaobo9 for code

**Comment by hailiang-wang** [comment]
@all-contributors  please add @zhangchanglong for eventOrganizing

**Comment by hailiang-wang** [comment]
@all-contributors please add @zhangchanglong for eventOrganizing

**Comment by hailiang-wang** [comment]
@all-contributors please add @SAMZONG for eventOrganizing,projectManagement,design.

**Comment by hailiang-wang** [comment]
@all-contributors please add @halfray for bug.

**Comment by hailiang-wang** [comment]
@all-contributors Please add @kely33 for bug.

**Comment by hailiang-wang** [comment]
@all-contributors please add @zjpzjp for code.

**Comment by hailiang-wang** [comment]
@all-contributors please add @lecjy for mentoring, maintenance, code.

**Comment by hailiang-wang** [comment]
@all-contributors please add @CollectBugs for code.

**Comment by hailiang-wang** [comment]
@all-contributors please add @zhangjian4 for bug.
