### ISSUE TITLE
机器人解析用户意图源码在项目中的哪里能看到

### ISSUE THREAD

**Issue by ZhuoYue89** [chatopera/cskefu#658]
## 描述

 想学习一下机器人解析意图并回应出设定语句的代码逻辑和算法
 请问机器人解析用户意图的源码在项目中的哪里能看到  找了半天只发现机器人功能是个插件 没找到具体运行业务逻辑的源码
## 操作系统

- [ ] macOS or Mac OSX
- [1 ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 代码版本

osc分支
## 关于春松客服

- 春松客服：做好开源客服系统

[https://dwz.chatopera.com/7VLF0B](https://dwz.chatopera.com/7VLF0B)

- 《春松客服大讲堂》：面向开发者的免费视频教程来了

[https://dwz.chatopera.com/19K4R](https://dwz.chatopera.com/19K4R)

## Open Source for the World by Chatopera

[![chatoper banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/144734473-df8ec8dd-ad0b-400f-8542-e4d40fb96375.jpg
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
Chatopera 机器人平台没有开源，您说的源码是闭源的。

但是我们分享了一些原理，Chatopera 多轮对话的实现参考：

https://docs.chatopera.com/products/chatbot-platform/explanations/index.html
