### ISSUE TITLE
重启后，netty-socket端口被占用

### ISSUE THREAD

**Issue by zc1813400107** [chatopera/cskefu#662]
netty-socket重启端口被占用问题
[![q0kJxI.png](https://s1.ax1x.com/2022/03/27/q0kJxI.png)](https://imgtu.com/i/q0kJxI)

**Comment by hailiang-wang** [comment]
第一次启动的时候，没有这个提示？

**Comment by zc1813400107** [comment]
是的

**Comment by hailiang-wang** [comment]
那就证明，重启的过程，没有正常的结束服务。可以通过检查该端口正在被哪个程序占用，就是查看使用该端口的 PID 确定。

昨天你遇到的问题，ElasticSearch 配置报错的情况，请创建一个 Issue 并补充后来的解决方案。

**Comment by zc1813400107** [comment]
试过了，杀掉端口进程没有任何用处，相关代码已提交

**Comment by zc1813400107** [comment]
甚至重启电脑也是没有任何用处的

**Comment by hailiang-wang** [comment]
@all-contributors please add @zc1813400107  for code, doc

**Comment by Functional-Account** [comment]
Closed
