### ISSUE TITLE
ElasticSearch 配置环境问题

### ISSUE THREAD

**Issue by zc1813400107** [chatopera/cskefu#663]
es启动错误
[![q0ZYtS.png](https://s1.ax1x.com/2022/03/27/q0ZYtS.png)](https://imgtu.com/i/q0ZYtS)

**Comment by zc1813400107** [comment]
解决方案 ：大概意思是说 ，没有成功的去加载一个es节点  

解决方法：

1. 将端口配置正确，如果是使用春松文档中的docker ,则可以使用8040端口
2. 还是不行则可以使用以下代码来忽略对es的检查
 `spring.data.elasticsearch.properties.client.transport.ignore_cluster_name=true`

**Comment by Functional-Account** [comment]
这个图片，图片复制到粘贴板后，可以 Copy + V 直接粘贴到 GitHub issue.

![image](https://user-images.githubusercontent.com/3538629/160805618-1d72fb01-ad41-4af1-b288-afa7180b1263.png)

**Comment by hailiang-wang** [comment]
Closed.

@hailiang-wang
