### ISSUE TITLE
ActiveMq启动报错

### ISSUE THREAD

**Issue by zc1813400107** [chatopera/cskefu#665]
[![q0e1gJ.png](https://s1.ax1x.com/2022/03/27/q0e1gJ.png)](https://imgtu.com/i/q0e1gJ)

**Comment by zc1813400107** [comment]
大概意思是启动消息监失败
解决方法 ：
​     1.原因：activeMq  的端口配置错误，方法：将ActiveMq的端口设置为正确的即可，如若用春松文档中的docker搭建的基础环境，则是使用8052端口

**Comment by hailiang-wang** [comment]
在上周，开发环境的搭建的文档有大量的补充和优化，包括 ActiveMQ 的配置和使用：

https://docs.chatopera.com/products/cskefu/osc/engineering.html

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。
