### ISSUE TITLE
人工坐席接入欢迎消息 web im 没起作用

### ISSUE THREAD

**Issue by yesidi** [chatopera/cskefu#668]
希望达到效果是，客服接入之后，自动发送一句欢迎语给客户。怎么设置？

**Comment by yesidi** [comment]
非提示语，而是客服自动发送一段欢迎的话出来。

**Comment by hailiang-wang** [comment]
目前还不支持，这个功能如果你们愿意实现，我们可以一起讨论，给出建设性意见，然后你们提交 PR。

**Comment by yesidi** [comment]
请问基于什么考量，这个设置不支持web im？
<img width="709" alt="image" src="https://user-images.githubusercontent.com/2936657/160373039-991ae3ae-2546-4c07-add9-b0bc3367f466.png">

**Comment by hailiang-wang** [comment]
@lecjy 这个任务先分配给你了，你研究一下，看看是否能解决。

**Comment by hailiang-wang** [comment]
@yesidi 这个工作已经更新到了最新的春松客服版本，使用升级文档，获得新功能。

https://docs.chatopera.com/products/cskefu/osc/maintainence.html

验证通过后，请关闭本 Issue，thanks.

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

**Comment by yesidi** [comment]
感谢修复。checked
