### ISSUE TITLE
网站渠道接入的网页有国际化支持么？

### ISSUE THREAD

**Issue by kingStrong2022** [chatopera/cskefu#679]
![IMAGE 2022-04-08 11:34:26](https://user-images.githubusercontent.com/101569383/162364218-b9a06b5d-fd20-4529-9649-559219b96b8f.jpg)
能把这个网页中的语言变成其他语言么？

**Comment by kingStrong2022** [comment]
还有访客的名称有办法动态设置么？

**Comment by hailiang-wang** [comment]
> 还有访客的名称有办法动态设置么？

每个问题一个 Issue，一件事情是一件事情。请帮忙再创建一个 Issue，感谢！

国际化，目前没有支持。
当然，作为开源项目，您可以在源码上改动，或者，您能做成可配置的，欢迎提交 PR！

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

**Comment by kingStrong2022** [comment]
好的
