### ISSUE TITLE
春松客服开源社区黑名单

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/cskefu#700]
严重违反社区理念，不尊重贡献者工作的，拉入黑名单。

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
![file](https://www.cskefu.com/wp-content/uploads/2022/04/image-1650793271421.png)

在春松客服开源社区协作中，一些人行为严重违反道德和开源宗旨，现对账号 GitHub [@vicviz](https://github.com/vicviz) 拉入春松客服开源社区黑名单，踢出春松客服开源社区所有协作交流工具。

## 谴责该用户行为

* 社区技术支持完成后，删除标题和问题描述

## 这些行为意味什么

春松客服核心开发者之所以愿意在 GitHub Issue 上解答问题，在于通过工单形式积累公开的知识，这样对于所有的春松客服用户有一个查询问题解决方案的位置，最大的降低重复劳动，以及更重要：春松客服用户可以自助式的解决问题。

**在我们给与支持后，更改工单内容，蓄意删除上下文，以致社区知识没有积累，让我们有限的支持浪费了，给了一个恬不知耻的人，给了一个低级趣味的人，给了一个素质低下的人。这极大的伤害了我们的感情，让我们对做好开源客服系统有了顾虑，我们必须有利的还击！**

以下使用**该小人**指代**该用户**。

## 该小人已经自甘堕落

* 联系该用户微信，恬不知耻的说为了安全

该小人的工单标题和日志，并无隐私数据，表示其来自何 IP，何机构。其标题是【会话监控和历史会话内容为空】；其日志是

```
| 2022-03-20 21:02:56.665 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find com.chatopera.cc.model.User with id 2c9380867f898b72017f917691304e5f; nested exception is javax.persistence.EntityNotFoundException: Unable to find com.chatopera.cc.model.User with id 2c938086***] with root cause [http-nio-8035-exec-1]
contact-center_1 | javax.persistence.EntityNotFoundException: Unable to find com.chatopera.cc.model.User with id 2c9380867f898b72017f917691304e5f
contact-center_1 | at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:144)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:227)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:262)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:121)
contact-center_1 | at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:89)
contact-center_1 | at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1129)
contact-center_1 | at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1022)
contact-center_1 | at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:639)
contact-center_1 | at org.hibernate.type.EntityType.resolve(EntityType.java:431)
contact-center_1 | at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:154)
contact-center_1 | at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:128)
contact-center_1 | at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1133)

```

该小人在微信上粉饰其行为的合理性：处于安全的考虑。我希望有一天你能看到，春松客服开源社区奉送给您两句话：

![file](https://www.cskefu.com/wp-content/uploads/2022/04/image-1650791700382.png)


* 鉴于该小人已于近日注销其 GitHub 账户，以销毁其不劳而获、自私自利的证据

该小人必然是自作孽不可活。

## 证实行为

* 删除标题关键词

![file](https://www.cskefu.com/wp-content/uploads/2022/04/image-1650790100524.png)

* 删除工单内容和日志

![file](https://www.cskefu.com/wp-content/uploads/2022/04/image-1650790109050.png)

**Comment by wangpengli** [comment]
无耻至极啊，做技术的这样搞，明显就是自绝生路，自掘坟墓，报应迟早到。

Hai Liang W. ***@***.***> 于2022年5月10日周二 12:13写道：
