### ISSUE TITLE
新增普通用户后，用户登录，看不到坐席状态

### ISSUE THREAD

**Issue by sdliudapei** [chatopera/cskefu#719]
## 描述

新增普通用户后，用户登录，看不到坐席状态
![image](https://user-images.githubusercontent.com/65060483/178393482-4789a654-e81f-45cf-8713-b59dcbc0d643.png)

![image](https://user-images.githubusercontent.com/65060483/178393433-28337cad-d9e6-41fd-963e-8764e8d8f36a.png)

![image](https://user-images.githubusercontent.com/65060483/178393531-003de072-044f-41ee-84f6-005f88d81dc2.png)

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
该测试角色进行【角色授权】。

参考：

- 系统初始化
https://docs.chatopera.com/products/cskefu/initialization.html

- 账号权限设计
[权限设计](https://docs.chatopera.com/products/cskefu/accounting.html#%E6%9D%83%E9%99%90%E8%AE%BE%E8%AE%A1)

**Comment by sdliudapei** [comment]
![image](https://user-images.githubusercontent.com/65060483/178394292-43235ad3-cb47-4f06-bbc4-ea5f384b3c24.png)
yiji已经设置过授权了，还是看不到，所以才提交的工单

**Comment by hailiang-wang** [comment]
权限设计后，新账号重新登录一下。
每次重新登录后，账号会从数据拉取最新的权限信息到缓存。
默认每24小时，会踢出登录账号，强制重新登录。

**Comment by hailiang-wang** [comment]
坐席账号创建时，需要制定为：多媒体坐席。

![image](https://user-images.githubusercontent.com/3538629/178395055-ab69bcda-7932-479d-aab9-82134ea6183f.png)

**Comment by sdliudapei** [comment]
收到
