### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by selfconfidence** [chatopera/cskefu#729]
按照部署文档的进行搭建后，出现跨域问题。
访问默认端口 8035 进入控制台的时候 看了下 soket 链接跨域了。
![1659152197329](https://user-images.githubusercontent.com/43275963/181871003-1451de0c-94ef-47f7-a327-6980d740018e.png)

服务器: 阿里云服务器；访问公网访问；
os：
![1659152309768](https://user-images.githubusercontent.com/43275963/181871159-86505f8b-aab7-44c3-b790-f61efab29feb.png)

**Comment by hailiang-wang** [comment]
阿里云安全组配置一下 8036 端口，允许 下行。

**Comment by selfconfidence** [comment]
![1659161836174](https://user-images.githubusercontent.com/43275963/181877449-caf4d4ad-a6c5-495a-9f89-44de043f8aba.png)

可以了，需要这样配置下.
