### ISSUE TITLE
maven打包的时候报错

### ISSUE THREAD

**Issue by sdliudapei** [chatopera/cskefu#730]
## 描述

[ERROR] Failed to execute goal on project contact-center: Could not resolve dependencies for project com.chatopera.cc:contact-center:war:7.0.0-SNAPSHOT: Failure to find com.chatopera.cc:contact-center:jar:7.0.0-SNAPSHOT in https://nexus.chatopera.com/repository/maven-public/ was cached in the local repository, resolution will not be reattempted until the update interval of chatopera has elapsed or updates are forced -> [Help 1]

## 操作系统

- [ ] macOS or Mac OSX
- [x] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
```Failure to find com.chatopera.cc:contact-center:jar:7.0.0-SNAPSHOT
```

这个包是你在本地构建的，不是依赖。

具体执行 mvn 打包的过程描述一下。

**Comment by hailiang-wang** [comment]
确保打包时，网络可访问到：

https://nexus.chatopera.com/#browse/browse:maven-public

**Comment by sdliudapei** [comment]
![image](https://user-images.githubusercontent.com/65060483/182985533-cc302ce8-9c16-4eee-bbde-20d62210433f.png)
com.chatopera.cc:contact-center:jar:7.0.0-SNAPSHOT这个从项目开始构建的时候就存在，maven先是clean,然后install或者compile都会报上面的错误。
网络可以访问到https://nexus.chatopera.com/#browse/browse:maven-public

**Comment by hailiang-wang** [comment]
春松客服 contact-center pom 文件，

https://github.com/chatopera/cskefu/blob/osc/contact-center/app/pom.xml

和上图不一样，在春松客服 contact-center pom 中，并不存在 error 中指定的依赖，建议：

* 使用春松客服最新代码
* 上传出错的 pom 文件

**Comment by sdliudapei** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatopera/cskefu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月5日(星期五) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatopera/cskefu] maven打包的时候报错 (Issue #730)





 
春松客服 contact-center pom 文件，
 
https://github.com/chatopera/cskefu/blob/osc/contact-center/app/pom.xml
 
和上图不一样，在春松客服 contact-center pom 中，并不存在 error 中指定的依赖，建议：
  
使用春松客服最新代码
 
上传出错的 pom 文件

**Comment by sdliudapei** [comment]
[pom.zip](https://github.com/chatopera/cskefu/files/9264707/pom.zip)

**Comment by hailiang-wang** [comment]
经过比对，您的 contact center 的 POM 需要更新：去掉框中内容。

![image](https://user-images.githubusercontent.com/3538629/182987860-24ad5bd2-593c-4da7-a8d8-8ad7d3b4056f.png)

**Comment by sdliudapei** [comment]
替换成了最新的pom,打包提示找不到.git文件，我查看开源代码，也没又发现这个文件，注掉.git的代码后，还是提示同样的错误
请问，这块有啥单独的配置吗
![image](https://user-images.githubusercontent.com/65060483/182988771-90cbe375-7876-4281-b08e-c58ba21b51a5.png)，

**Comment by sdliudapei** [comment]
不好意思，上图的代码没注全，现在可以正常打包了，我把plugin下pl.project13.maven整个注掉了，这个插件在系统中起到什么作用呢？？注掉会不会影响到系统的使用？

**Comment by hailiang-wang** [comment]
> 不好意思，上图的代码没注全，现在可以正常打包了，我把plugin下pl.project13.maven整个注掉了，这个插件在系统中起到什么作用呢？？注掉会不会影响到系统的使用？

影响不大，可以忽略。

**Comment by hailiang-wang** [comment]
插件 pl.project13.maven 会生成产品信息里的 build，build 绑定到 git commit id。


![image](https://user-images.githubusercontent.com/3538629/182993285-80ebc5e2-f37b-437b-8794-7259afc99e1e.png)

**Comment by sdliudapei** [comment]
收到，多谢大佬指点
