### ISSUE TITLE
想使用  chatopera-sample-java 项目中提出的心理咨询问答 API 但是打开文档中的链接后 404

### ISSUE THREAD

**Issue by huanghungsen** [chatopera/cskefu#731]
## 描述

![41da1a391c601ca51674ed715b66073](https://user-images.githubusercontent.com/41362561/183591205-1dc647f3-2181-493d-9309-172ae2cf2811.jpg)
![3e11ed427b47f82a9fc16f71acb2875](https://user-images.githubusercontent.com/41362561/183591240-821bf9e6-206c-4547-bc05-6b0c5e45c13b.jpg)
![d97072fa06ba34afd0f3f5d34b73296](https://user-images.githubusercontent.com/41362561/183591256-2c8b2eb9-a9a5-4876-9275-7e7872ec1b6c.jpg)

如果该API已经无法使用了，想问一下 贵公司还有没有 作为心理咨询问答相关的功能，如果有的话想和贵公司合作

## 操作系统

- [ ] macOS or Mac OSX
- [ ] Windows
- [ ] Linux(Debian, CentOS, Ubuntu, etc.)

## 祝福与不祝福

春松客服之所以开源，是基于这样一种信念：爱人也是爱己，利他也是利己。
对人和人美好关系的向往，对人潜力的信任。让我们相信因春松客服而受益的人，会回报给春松客服开源社区，我们[所有贡献者](https://github.com/chatopera/cskefu#%E8%B4%A1%E7%8C%AE%E8%80%85%E5%88%97%E8%A1%A8-)基于共赢的信念合作。
回报方式包括：[提交 PR](https://github.com/chatopera/cskefu/blob/osc/CONTRIBUTING.md)、购买春松客服相关的[付费产品和服务](https://www.chatopera.com/price.html)等。

因春松客服受益，而不回报开源社区的用户，我们不欢迎使用春松客服：我们开源并不是为了你们，你们是不被祝福的。

## Open Source for the World

[![banner][co-banner-image]][co-url]

[co-banner-image]: https://user-images.githubusercontent.com/3538629/159913838-fbed2a14-a735-45b3-9e48-4727780a0d96.png
[co-url]: https://www.chatopera.com

**Comment by hailiang-wang** [comment]
该项目已经停止，部分内容已经通过公开数据集共享：

https://github.com/chatopera/efaqa-corpus-zh

该项目为开放数据集，使用请注意声明中内容。
