### ISSUE TITLE
言简意赅，更容易获得帮助，比如问题简述及 root cause 日志语句，

### ISSUE THREAD

**Issue by zhangyanming0924** [chatopera/cskefu#736]
你好
想咨询下 客服项目在tomcat怎么部署

**Comment by hailiang-wang** [comment]
注意 Issue 标题，要按照需求描述。开出高质量的 Issue。
感谢。


## 推荐按照官方文档部署：
https://docs.chatopera.com/products/cskefu/deploy.html

## 如果要使用 WAR 部署，参考：

* WAR 打包脚本：https://github.com/chatopera/cskefu/blob/osc/contact-center/admin/build.sh
* Docker 镜像构建：https://github.com/chatopera/cskefu/blob/osc/contact-center/Dockerfile

**Comment by hailiang-wang** [comment]
春松客服是面向云原生环境的客服系统。

* 开发环境：https://docs.chatopera.com/products/cskefu/osc/engineering.html
* 运维：https://docs.chatopera.com/products/cskefu/osc/maintainence.html

**Comment by zhangyanming0924** [comment]
好的  谢谢老师
